version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
    exclude_patterns:
      - 'cypress/{integration,support}/**/*.js'
      # The line below should work but doesn't it removes all js and jsx quality checking
      # - 'src/**/*.{test,stories}.{js,jsx}'
exclude_patterns:
  - '**/node_modules/'
  - 'src/app/lib/config/'
  - 'src/app/**/fixtures.js'
  - 'scripts/signBuild.js'
  - 'scripts/lighthouseBudget.test.js'
  - 'scripts/lighthouseBudget.js'
  - 'scripts/dependencyCheck.js'
  - 'scripts/simorghPages.js'
  - 'scripts/simorghLaunchDates.js'
