const news = {
  a: "a",
  an: "an",
  the: "the",
  he: "he",
  she: "she",
  it: "it",
  her: "her",
  his: "his",
  we: "we",
  they: "they",
  me: "me",
  us: "us",
  them: "them",
  you: "you",
  I: "I",
  myself: "myself",
  yourself: "yourself",
  himself: "himself",
  herself: "herself",
  itself: "itself",
  ourselves: "ourselves",
  yourselves: "yourselves",
  themselves: "themselves",
  who: "who",
  whom: "whom",
  whose: "whose",
  which: "which",
  what: "what",
  someone: "someone",
  anyone: "anyone",
  everyone: "everyone",
  and: "and",
  but: "but",
  or: "or",
  nor: "nor",
  yet: "yet",
  so: "so",
  however: "however",
  because: "because",
  although: "although",
  though: "though",
  since: "since",
  if: "if",
  unless: "unless",
  while: "while",
  whereas: "whereas",
  in: "in",
  on: "on",
  at: "at",
  by: "by",
  for: "for",
  with: "with",
  to: "to",
  of: "of",
  as: "as",
  between: "between",
  through: "through",
  about: "about",
  into: "into",
  onto: "onto",
  upon: "upon",
  beside: "beside",
  behind: "behind",
  within: "within",
  is: "is",
  are: "are",
  was: "was",
  were: "were",
  am: "am",
  be: "be",
  being: "being",
  been: "been",
  has: "has",
  have: "have",
  had: "had",
  do: "do",
  does: "does",
  did: "did",
  will: "will",
  would: "would",
  shall: "shall",
  should: "should",
  can: "can",
  could: "could",
  may: "may",
  might: "might",
  must: "must",
  here: "here",
  there: "there",
  then: "then",
  now: "now",
  very: "very",
  too: "too",
  always: "always",
  never: "never",
  sometimes: "sometimes",
  often: "often",
  seldom: "seldom",
  usually: "usually",
  already: "already",
  yet: "yet",
  soon: "soon",
  late: "late",
  this: "this",
  that: "that",
  these: "these",
  those: "those",
  some: "some",
  any: "any",
  no: "no",
  all: "all",
  few: "few",
  many: "many",
  most: "most",
  much: "much",
  such: "such",
  each: "each",
  every: "every",
  both: "both",
  either: "either",
};

const afaanoromoo = {
  a: "tokko",
  an: "tokko",
  the: "kan",
  he: "inni",
  she: "isheen",
  it: "inni",
  her: "ishee",
  his: "isaa",
  we: "nu",
  they: "isaan",
  me: "ani",
  us: "nuti",
  them: "isan",
  you: "attee",
  I: "ani",
  myself: "ofii koo",
  yourself: "ofii kee",
  himself: "ofii isaa",
  herself: "ofii ishee",
  itself: "ofii isaa",
  ourselves: "ofii keenyaa",
  yourselves: "ofii keessan",
  themselves: "ofii isaanii",
  who: "eenyuu",
  whom: "eenyu",
  whose: "eenyummaa",
  which: "kan",
  what: "maal",
  someone: "namni tokko",
  anyone: "namni kamiyyuu",
  everyone: "namni hunda",
  and: "fi",
  but: "garuu",
  or: "yookaan",
  nor: "yookaan hin",
  yet: "garuu",
  so: "kanaaf",
  however: "garuu",
  because: "sababiin",
  although: "yoo ta'e",
  though: "garuu",
  since: "akka",
  if: "yoo",
  unless: "yoo hin ta'in",
  while: "yeroo",
  whereas: "akkasumas",
  in: "keessatti",
  on: "irratti",
  at: "itti",
  by: "biratti",
  for: "fayyadamuuf",
  with: "wajjin",
  to: "itti",
  of: "kan",
  as: "akka",
  between: "gidduu",
  through: "kallattiin",
  about: "waa'ee",
  into: "itti",
  onto: "irratti",
  upon: "irratti",
  beside: "gara",
  behind: "duubatti",
  within: "keessatti",
  is: "ta'ee",
  are: "ta'an",
  was: "ta'e",
  were: "ta'an",
  am: "ani",
  be: "ta'uu",
  being: "ta'uu",
  been: "ta'ee",
  has: "qabaa",
  have: "qabduu",
  had: "qabaa ture",
  do: "gochuu",
  does: "gochuu",
  did: "gochaa ture",
  will: "ni ta'a",
  would: "ta'a ture",
  shall: "ta'uu",
  should: "ta'uu qaba",
  can: "danda'a",
  could: "danda'e",
  may: "ni danda'aa",
  might: "danda'aa ture",
  must: "dirqama",
  here: "as irratti",
  there: "achitti",
  then: "bakka biraa",
  now: "amma",
  very: "baay'ee",
  too: "ilmaan",
  always: "yeroo hunda",
  never: "hin ta'u",
  sometimes: "yeroo tokko tokko",
  often: "baay'ee",
  seldom: "yeroo muraasa",
  usually: "yeroo baay'ee",
  already: "duraa",
  yet: "amma",
  soon: "boodarra",
  late: "duubatti",
  this: "kana",
  that: "sun",
  these: "kunniin",
  those: "sunnis",
  some: "tokkoffaa",
  any: "kamiyyuu",
  no: "lakkii",
  all: "hunda",
  few: "xiqqoo",
  many: "baay'ee",
  most: "baay'ina",
  much: "baay'ee",
  such: "akkasii",
  each: "tokko tokko",
  every: "hunda",
  both: "lamaanuu",
  either: "yookaan",
};

const afrique = {
  a: "un|une",
  an: "un|une",
  the: "le|la|les",
  he: "il",
  she: "elle",
  it: "il|elle",
  her: "sa|ses",
  his: "son|ses",
  we: "nous",
  they: "ils|elles",
  me: "me",
  us: "nous",
  them: "les|leur",
  you: "tu|vous",
  I: "je",
  myself: "moi-même",
  yourself: "toi-même|vous-même",
  himself: "lui-même",
  herself: "elle-même",
  itself: "soi-même",
  ourselves: "nous-mêmes",
  yourselves: "vous-mêmes",
  themselves: "eux-mêmes|elles-mêmes",
  who: "qui",
  whom: "qui|à qui",
  whose: "à qui|dont",
  which: "quel|quelle",
  what: "quoi|que",
  someone: "quelqu'un",
  anyone: "n'importe qui",
  everyone: "tout le monde",
  and: "et",
  but: "mais",
  or: "ou",
  nor: "ni",
  yet: "cependant",
  so: "donc",
  however: "cependant",
  because: "parce que",
  although: "bien que",
  though: "quoique",
  since: "depuis|puisque",
  if: "si",
  unless: "à moins que",
  while: "tandis que",
  whereas: "alors que",
  in: "dans",
  on: "sur",
  at: "à",
  by: "par",
  for: "pour",
  with: "avec",
  to: "à",
  of: "de",
  as: "comme",
  between: "entre",
  through: "à travers",
  about: "sur",
  into: "dans",
  onto: "sur",
  upon: "sur",
  beside: "à côté de",
  behind: "derrière",
  within: "dans",
  is: "est",
  are: "sont",
  was: "était",
  were: "étaient",
  am: "suis",
  be: "être",
  being: "étant",
  been: "été",
  has: "a",
  have: "avoir",
  had: "avait",
  do: "faire",
  does: "fait",
  did: "fait",
  will: "sera",
  would: "serait",
  shall: "sera",
  should: "devrait",
  can: "peut",
  could: "pourrait",
  may: "peut",
  might: "pourrait",
  must: "doit",
  here: "ici",
  there: "là",
  then: "alors",
  now: "maintenant",
  very: "très",
  too: "trop",
  always: "toujours",
  never: "jamais",
  sometimes: "parfois",
  often: "souvent",
  seldom: "rarement",
  usually: "habituellement",
  already: "déjà",
  yet: "encore",
  soon: "bientôt",
  late: "en retard",
  this: "ce|cette|ces",
  that: "ce|cela|celui",
  these: "ces",
  those: "ceux|celles",
  some: "quel|ques",
  any: "n'importe quel",
  no: "non",
  all: "tout",
  few: "peu",
  many: "beaucoup",
  most: "la plupart",
  much: "beaucoup",
  such: "tel",
  each: "chaque",
  every: "chaque",
  both: "les deux",
  either: "soit",
};

const amharic = {
  a: "አንድ",
  an: "አንድ",
  the: "እንደ",
  he: "እሱ",
  she: "እሷ",
  it: "እሱ",
  her: "እሷ",
  his: "እሱ",
  we: "እኛ",
  they: "እነሱ",
  me: "እኔ",
  us: "እኛ",
  them: "እነሱ",
  you: "አንተ|እሱ",
  I: "እኔ",
  myself: "ራሴ",
  yourself: "ራስህ|ራስሽ",
  himself: "ራሱ",
  herself: "ራሷ",
  itself: "ራሱ",
  ourselves: "ራሳችን",
  yourselves: "ራሳችሁ",
  themselves: "ራሳቸው",
  who: "ማን",
  whom: "ማንን",
  whose: "ማንኛው",
  which: "የማንኛው",
  what: "ምን",
  someone: "ማንም",
  anyone: "ማንም",
  everyone: "ሁሉም",
  and: "እና",
  but: "ነገር ግን",
  or: "ወይም",
  nor: "እንደምንም",
  yet: "እስካሁን",
  so: "ስለዚህ",
  however: "በሆነ ቢሆንም",
  because: "ምክንያት",
  although: "ቢሆንም",
  though: "ነገር ግን",
  since: "ጀምሮ",
  if: "ከሆነ",
  unless: "እስኪከሆነ",
  while: "ስለሆነ",
  whereas: "ስለሆነ",
  in: "በ",
  on: "ላይ",
  at: "ላይ",
  by: "በ",
  for: "ስለ",
  with: "ጋር",
  to: "ወደ",
  of: "እንደ",
  as: "እንደ",
  between: "መካከል",
  through: "በመካከል",
  about: "ስለ",
  into: "ወደ",
  onto: "ላይ",
  upon: "ላይ",
  beside: "በአካባቢ",
  behind: "ከተከተ",
  within: "ውስጥ",
  is: "ነው",
  are: "ናቸው",
  was: "ነበረ",
  were: "ነበሩ",
  am: "ነኝ",
  be: "ሆን",
  being: "እንደነበረ",
  been: "ነበረ",
  has: "አለ",
  have: "አለኝ",
  had: "ነበረ",
  do: "አድርግ",
  does: "ይሁን",
  did: "አደረገ",
  will: "እንደምን",
  would: "እንደምን",
  shall: "ይሁን",
  should: "ሆኖ",
  can: "መች",
  could: "ማለት",
  may: "እንደሆነ",
  might: "ማለት",
  must: "ሆኖ",
  here: "እዚህ",
  there: "እስከ",
  then: "በኋላ",
  now: "አሁን",
  very: "በጣም",
  too: "በጣም",
  always: "ሁልጊዜ",
  never: "በተለምዶ",
  sometimes: "አንዳንድ ጊዜ",
  often: "በተለምዶ",
  seldom: "አንዳንድ ጊዜ",
  usually: "በመነሻ",
  already: "በማኅበረሰቡ",
  yet: "እስካሁን",
  soon: "በቅርብ",
  late: "ከመነሻ",
  this: "ይህ",
  that: "ስለዚህ",
  these: "እነሆ",
  those: "እነሆ",
  some: "በመነሻ",
  any: "በመነሻ",
  no: "አይ",
  all: "ሁሉ",
  few: "ማንኛው",
  many: "በተለምዶ",
  most: "በሆነ",
  much: "በመነሻ",
  such: "እንደምንም",
  each: "በመነሻ",
  every: "ሁሉ",
  both: "አንዱ",
  either: "እንደሆነ",
};

const arabic = {
  a: "واحد",
  an: "واحد",
  the: "ال",
  he: "هو",
  she: "هي",
  it: "هو|هي",
  her: "لها",
  his: "له",
  we: "نحن",
  they: "هم",
  me: "أنا",
  us: "نحن",
  them: "هم",
  you: "أنت|أنتم",
  I: "أنا",
  myself: "نفسي",
  yourself: "نفسك",
  himself: "نفسه",
  herself: "نفسها",
  itself: "نفسه",
  ourselves: "أنفسنا",
  yourselves: "أنفسكم",
  themselves: "أنفسهم",
  who: "من",
  whom: "من",
  whose: "لمن",
  which: "أي",
  what: "ما",
  someone: "أحد",
  anyone: "أي شخص",
  everyone: "الجميع",
  and: "و",
  but: "لكن",
  or: "أو",
  nor: "ولا",
  yet: "لكن",
  so: "إذن",
  however: "مع ذلك",
  because: "لأن",
  although: "على الرغم من",
  though: "على الرغم من",
  since: "منذ",
  if: "إذا",
  unless: "إلا إذا",
  while: "بينما",
  whereas: "بينما",
  in: "في",
  on: "على",
  at: "في",
  by: "بواسطة",
  for: "من أجل",
  with: "مع",
  to: "إلى",
  of: "من",
  as: "كـ",
  between: "بين",
  through: "من خلال",
  about: "عن",
  into: "إلى",
  onto: "إلى",
  upon: "على",
  beside: "بجانب",
  behind: "وراء",
  within: "داخل",
  is: "هو",
  are: "هم",
  was: "كان",
  were: "كانوا",
  am: "أنا",
  be: "كن",
  being: "يكون",
  been: "كان",
  has: "لديه",
  have: "لدي",
  had: "كان لدى",
  do: "فعل",
  does: "يفعل",
  did: "فعل",
  will: "سوف",
  would: "سوف",
  shall: "يجب",
  should: "يجب",
  can: "يمكن",
  could: "يمكن",
  may: "قد",
  might: "قد",
  must: "يجب",
  here: "هنا",
  there: "هناك",
  then: "ثم",
  now: "الآن",
  very: "جداً",
  too: "أيضاً",
  always: "دائماً",
  never: "أبداً",
  sometimes: "أحياناً",
  often: "غالباً",
  seldom: "نادراً",
  usually: "عادة",
  already: "بالفعل",
  yet: "حتى الآن",
  soon: "قريباً",
  late: "متأخراً",
  this: "هذا|هذه",
  that: "ذلك|تلك",
  these: "هؤلاء",
  those: "أولئك",
  some: "بعض",
  any: "أي",
  no: "لا",
  all: "كل",
  few: "قليل",
  many: "كثير",
  most: "أغلب",
  much: "كثير",
  such: "مثل",
  each: "كل",
  every: "كل",
  both: "كلاهما",
  either: "إما",
};

const azeri = {
  a: "bir",
  an: "bir",
  the: "bu",
  he: "o",
  she: "o",
  it: "o",
  her: "onun",
  his: "onun",
  we: "biz",
  they: "onlar",
  me: "məni",
  us: "bizi",
  them: "onları",
  you: "sən|siz",
  I: "mən",
  myself: "özüm",
  yourself: "özün",
  himself: "özünü",
  herself: "özünü",
  itself: "özünü",
  ourselves: "özümüz",
  yourselves: "özünüz",
  themselves: "özlərini",
  who: "kim",
  whom: "kimə",
  whose: "kimindir",
  which: "hansı",
  what: "nə",
  someone: "birisi",
  anyone: "hər hansı biri",
  everyone: "hər kəs",
  and: "və",
  but: "amma",
  or: "və ya",
  nor: "ya da",
  yet: "amma",
  so: "beləliklə",
  however: "lakin",
  because: "çünki",
  although: "baxmayaraq",
  though: "amma",
  since: "bəri",
  if: "əgər",
  unless: "əgər olmazsa",
  while: "ikən",
  whereas: "halbuki",
  in: "daxilində",
  on: "üzərində",
  at: "da",
  by: "tərəfindən",
  for: "üçün",
  with: "ilə",
  to: "ədək",
  of: "dən",
  as: "kimi",
  between: "arasında",
  through: "üzerinden",
  about: "haqqında",
  into: "daxil",
  onto: "üzərinə",
  upon: "üzərinə",
  beside: "yanında",
  behind: "arxasında",
  within: "içində",
  is: "dir",
  are: "dir",
  was: "idi",
  were: "idilər",
  am: "əm",
  be: "ol",
  being: "olmaq",
  been: "olmuş",
  has: "var",
  have: "var",
  had: "vardı",
  do: "etmək",
  does: "edir",
  did: "etdi",
  will: "olacaq",
  would: "olardı",
  shall: "olmalı",
  should: "olmalı",
  can: "bilmək",
  could: "bilmək",
  may: "ola bilər",
  might: "ola bilər",
  must: "olmalıdır",
  here: "burada",
  there: "orada",
  then: "sonra",
  now: "indi",
  very: "çox",
  too: "çox",
  always: "həmişə",
  never: "heç vaxt",
  sometimes: "bəzən",
  often: "tez-tez",
  seldom: "nadiren",
  usually: "adətən",
  already: "artıq",
  yet: "hələ",
  soon: "yaxında",
  late: "gec",
  this: "bu",
  that: "o",
  these: "bunlar",
  those: "onlar",
  some: "bəziləri",
  any: "hər hansı",
  no: "yox",
  all: "hamısı",
  few: "bir neçə",
  many: "çox",
  most: "əksəriyyət",
  much: "çox",
  such: "belə",
  each: "hər",
  every: "hər",
  both: "hər ikisi",
  either: "ya da",
};

const bengali = {
  a: "একটি",
  an: "একটি",
  the: "দ্য",
  he: "সে",
  she: "সে",
  it: "এটা",
  her: "তার",
  his: "তার",
  we: "আমরা",
  they: "তারা",
  me: "আমাকে",
  us: "আমাদের",
  them: "তাদের",
  you: "তুমি|আপনি",
  I: "আমি",
  myself: "নিজেকে",
  yourself: "নিজেকে",
  himself: "নিজেকে",
  herself: "নিজেকে",
  itself: "নিজেকে",
  ourselves: "নিজেদের",
  yourselves: "নিজেদের",
  themselves: "নিজেদের",
  who: "কে",
  whom: "কাকে",
  whose: "কার",
  which: "কোন",
  what: "কি",
  someone: "কেউ",
  anyone: "কেউ",
  everyone: "সবাই",
  and: "এবং",
  but: "কিন্তু",
  or: "অথবা",
  nor: "না",
  yet: "তবে",
  so: "তাহলে",
  however: "যাহোক",
  because: "কারণ",
  although: "যদিও",
  though: "যদিও",
  since: "যেহেতু",
  if: "যদি",
  unless: "যতক্ষণ না",
  while: "যতক্ষণ না",
  whereas: "অথবা",
  in: "ভিতরে",
  on: "উপর",
  at: "এতে",
  by: "দ্বারা",
  for: "জন্য",
  with: "সহ",
  to: "প্রতি",
  of: "এর",
  as: "হিসেবে",
  between: "মধ্যে",
  through: "মাধ্যমে",
  about: "সম্পর্কে",
  into: "ভিতরে",
  onto: "উপর",
  upon: "উপর",
  beside: "পার্শ্বে",
  behind: "পিছনে",
  within: "মাঝে",
  is: "হয়",
  are: "হয়",
  was: "ছিল",
  were: "ছিল",
  am: "হই",
  be: "হওয়া",
  being: "হওয়া",
  been: "ছিল",
  has: "আছে",
  have: "আছে",
  had: "ছিল",
  do: "করতে",
  does: "করে",
  did: "করল",
  will: "হবে",
  would: "হত",
  shall: "হবে",
  should: "চাই",
  can: "পারবে",
  could: "পারবে",
  may: "হতে পারে",
  might: "হতে পারে",
  must: "যেতে হবে",
  here: "এখানে",
  there: "সেখানে",
  then: "তখন",
  now: "এখন",
  very: "খুব",
  too: "অত্যন্ত",
  always: "সর্বদা",
  never: "কখনও না",
  sometimes: "কখনও কখনও",
  often: "প্রায়ই",
  seldom: "দুর্লভ",
  usually: "সাধারণত",
  already: "ইতিমধ্যে",
  yet: "এখনও",
  soon: "শীঘ্রই",
  late: "বিলম্ব",
  this: "এটা",
  that: "সেটা",
  these: "এইগুলি",
  those: "ওগুলি",
  some: "কিছু",
  any: "যেকোনো",
  no: "না",
  all: "সব",
  few: "কিছু",
  many: "অনেক",
  most: "অধিকাংশ",
  much: "অনেক",
  such: "এমন",
  each: "প্রত্যেক",
  every: "প্রত্যেক",
  both: "দুটি",
  either: "অথবা",
};

const burmese = {
  a: "တစ်",
  an: "တစ်",
  the: "အေ",
  he: "သူ",
  she: "သူမ",
  it: "ဒါ",
  her: "သူမ၏",
  his: "သူ၏",
  we: "ကျွန်ုပ်တို့",
  they: "သူတို့",
  me: "ကျွန်ုပ်ကို",
  us: "ကျွန်ုပ်တို့ကို",
  them: "သူတို့ကို",
  you: "နင်|သင်",
  I: "ကျွန်တော်",
  myself: "ကျွန်တော်ကိုယ်တိုင်",
  yourself: "သင်ကိုယ်တိုင်",
  himself: "သူကိုယ်တိုင်",
  herself: "သူမကိုယ်တိုင်",
  itself: "ဒါကိုယ်တိုင်",
  ourselves: "ကျွန်တော်တို့ကိုယ်တိုင်",
  yourselves: "သင်တို့ကိုယ်တိုင်",
  themselves: "သူတို့ကိုယ်တိုင်",
  who: "ဘယ်သူ",
  whom: "ဘယ်သူကို",
  whose: "ဘယ်သူ၏",
  which: "ဘယ်",
  what: "ဘာ",
  someone: "တစ်ဦး",
  anyone: "သူတစ်ပါး",
  everyone: "အားလုံး",
  and: "နဲ့",
  but: "ဒါပေမယ့်",
  or: "သို့မဟုတ်",
  nor: "လည်းမဟုတ်",
  yet: "သို့သော်လည်း",
  so: "ဒါကြောင့်",
  however: "သို့သော်လည်း",
  because: "အကြောင်း",
  although: "သို့ရာတွင်",
  though: "သို့သော်လည်း",
  since: "စဉ်",
  if: "မဟုတ်ရင်",
  unless: "မဖြစ်ခဲ့ရင်",
  while: "လေ့လာချိန်",
  whereas: "သို့ရာတွင်",
  in: "အတွင်း",
  on: "ပေါ်",
  at: "၌",
  by: "မှ",
  for: "အတွက်",
  with: "နှင့်",
  to: "သို့",
  of: "၏",
  as: "အဖြစ်",
  between: "အကြား",
  through: "မှတဆင့်",
  about: "အကြောင်း",
  into: "အတွင်း",
  onto: "ပေါ်သို့",
  upon: "အပေါ်",
  beside: "အနီး",
  behind: "အောက်",
  within: "အတွင်း",
  is: "ဖြစ်သည်",
  are: "ဖြစ်သည်",
  was: "ဖြစ်ခဲ့သည်",
  were: "ဖြစ်ခဲ့သည်",
  am: "ဖြစ်သည်",
  be: "ဖြစ်ပါ",
  being: "ဖြစ်နေသည်",
  been: "ဖြစ်ခဲ့သည်",
  has: "ရှိသည်",
  have: "ရှိသည်",
  had: "ရှိခဲ့သည်",
  do: "လုပ်သည်",
  does: "လုပ်သည်",
  did: "လုပ်ခဲ့သည်",
  will: "ဖြစ်မည်",
  would: "ဖြစ်မည်",
  shall: "ဖြစ်ရမည်",
  should: "ဖြစ်ရမည်",
  can: "နိုင်သည်",
  could: "နိုင်သည်",
  may: "ဖြစ်နိုင်သည်",
  might: "ဖြစ်နိုင်သည်",
  must: "သင့်တော်သည်",
  here: "ဒီမှာ",
  there: "ထိုနေရာတွင်",
  then: "ထိုအခါ",
  now: "အခု",
  very: "မိုက်",
  too: "လွန်လွန်း",
  always: "အစဉ်",
  never: "မဖြစ်ကြောင်း",
  sometimes: "တခါတလေ",
  often: "အတော်",
  seldom: "မကြာခဏ",
  usually: "ပုံမှန်အားဖြင့်",
  already: "ပြီးခဲ့သည်",
  yet: "သို့သော်လည်း",
  soon: "အလျင်",
  late: "ကြာမြင့်",
  this: "ဒီ",
  that: "အဲ့",
  these: "ဤများ",
  those: "သူတို့",
  some: "အချို့",
  any: "တစ်ခုခု",
  no: "မဟုတ်ပါ",
  all: "အားလုံး",
  few: "တချို့",
  many: "အများ",
  most: "အများဆုံး",
  much: "အများကြီး",
  such: "ဤကဲ့သို့",
  each: "တစ်ခုချင်း",
  every: "တစ်ခုချင်း",
  both: "နှစ်ဦး",
  either: "တစ်ခုခု",
};

const gahuza = {
  a: "imwe",
  an: "imwe",
  the: "iyo",
  he: "we",
  she: "iye",
  it: "iri",
  her: "ya",
  his: "ya",
  we: "turi",
  they: "bari",
  me: "nje",
  us: "turi",
  them: "bari",
  you: "wewe",
  I: "nje",
  myself: "umwe",
  yourself: "umwe",
  himself: "umwe",
  herself: "umwe",
  itself: "umwe",
  ourselves: "twese",
  yourselves: "mwe",
  themselves: "bose",
  who: "ni nde",
  whom: "ni nde",
  whose: "ni we",
  which: "ni",
  what: "iki",
  someone: "umuntu",
  anyone: "umuntu wese",
  everyone: "abantu bose",
  and: "na",
  but: "ariko",
  or: "cyangwa",
  nor: "cyangwa",
  yet: "ariko",
  so: "bityo",
  however: "ariko",
  because: "kuko",
  although: "nubwo",
  though: "nubwo",
  since: "kubera",
  if: "niba",
  unless: "kandi",
  while: "mu gihe",
  whereas: "mu gihe",
  in: "mu",
  on: "ku",
  at: "kuri",
  by: "na",
  for: "kubera",
  with: "na",
  to: "kugera",
  of: "cyo",
  as: "nk’uko",
  between: "hagati",
  through: "binyura",
  about: "kuri",
  into: "mu",
  onto: "ku",
  upon: "ku",
  beside: "kuri",
  behind: "inyuma",
  within: "mu",
  is: "ni",
  are: "ni",
  was: "byari",
  were: "byari",
  am: "ndi",
  be: "kuba",
  being: "kuba",
  been: "byari",
  has: "afite",
  have: "mfite",
  had: "yari",
  do: "kora",
  does: "akora",
  did: "yarakoze",
  will: "azaba",
  would: "yaba",
  shall: "nzaba",
  should: "ngomba",
  can: "ashobora",
  could: "ashobora",
  may: "bishoboka",
  might: "bishoboka",
  must: "ugomba",
  here: "hano",
  there: "hariho",
  then: "ubwo",
  now: "ubu",
  very: "cyane",
  too: "na",
  always: "ubwose",
  never: "nta gihe",
  sometimes: "bimwe na bimwe",
  often: "kenshi",
  seldom: "gake",
  usually: "akenshi",
  already: "byarabaye",
  yet: "kandi",
  soon: "vuba",
  late: "nyuma",
  this: "iki",
  that: "icyo",
  these: "ibi",
  those: "ibyo",
  some: "bimwe",
  any: "ikintu",
  no: "oya",
  all: "byose",
  few: "bake",
  many: "menshi",
  most: "nyinshi",
  much: "menshi",
  such: "nka",
  each: "buri",
  every: "buri",
  both: "byombi",
  either: "cyose",
};

const gujarati = {
  a: "એક",
  an: "એક",
  the: "દે",
  he: "એ",
  she: "તે",
  it: "તે",
  her: "તેણી",
  his: "તેનું",
  we: "અમે",
  they: "તે",
  me: "મને",
  us: "અમને",
  them: "તેમને",
  you: "તમે",
  I: "હું",
  myself: "હું પોતે",
  yourself: "તમારા",
  himself: "તેણે",
  herself: "તેને",
  itself: "તે",
  ourselves: "અમે પોતે",
  yourselves: "તમે",
  themselves: "તેને",
  who: "કોઈ",
  whom: "ક્યા",
  whose: "કૂનો",
  which: "કઈ",
  what: "શું",
  someone: "કોઈ",
  anyone: "કોઈ પણ",
  everyone: "પ્રતિ બધા",
  and: "અને",
  but: "પણ",
  or: "કે",
  nor: "કોઈ પણ નથી",
  yet: "હવે",
  so: "તેવું",
  however: "પરંતુ",
  because: "કારણ કે",
  although: "જોકે",
  though: "પણ",
  since: "તેથી",
  if: "જો",
  unless: "જો સુધી",
  while: "જ્યારે",
  whereas: "જ્યાં",
  in: "માં",
  on: "પર",
  at: "કિંબા",
  by: "સાથે",
  for: " માટે",
  with: "સાથે",
  to: "કુ",
  of: "નો",
  as: "જેમ",
  between: "દરમિયાન",
  through: "દ્વારા",
  about: "બारेમાં",
  into: "માં",
  onto: "પર",
  upon: "પર",
  beside: "બાજુમાં",
  behind: "પાછળ",
  within: "અંતર્ગત",
  is: "છે",
  are: "છે",
  was: "હતો",
  were: "હતા",
  am: "હું છું",
  be: "હોય",
  being: "હોવો",
  been: "હોય",
  has: "છે",
  have: "છે",
  had: "છેલ્લે",
  do: "કરવું",
  does: "કરે",
  did: "કર્યો",
  will: "હોય",
  would: "કરશે",
  shall: "હોઈ શકે છે",
  should: "જરૂરી છે",
  can: "શક્ય છે",
  could: "શક્ય છે",
  may: "હોઈ શકે છે",
  might: "હોઈ શકે છે",
  must: "જરૂરી છે",
  here: "અહીં",
  there: "ત્યાં",
  then: "એ પછી",
  now: "હવે",
  very: "ખૂબ",
  too: "ઘણું",
  always: "સૌંદર્ય",
  never: "કદાપિ",
  sometimes: "કદાચ",
  often: "વારંવાર",
  seldom: "કમ",
  usually: "સામાન્ય",
  already: "આગેઇ",
  yet: "હવે",
  soon: "ઝડપી",
  late: "વિલંબ",
  this: "આ",
  that: "તે",
  these: "આ",
  those: "તેઓ",
  some: "કેટલાય",
  any: "કોઈ પણ",
  no: "ના",
  all: "તમામ",
  few: "કમ",
  many: "ઘણાં",
  most: "પ્રમુખ",
  much: "ઘણું",
  such: "જેમ",
  each: "દરેક",
  every: "દરેક",
  both: "બધાં",
  either: "કે",
};

const hausa = {
  a: "wani",
  an: "wani",
  the: "na",
  he: "shi",
  she: "ita",
  it: "shi",
  her: "ta",
  his: "nasa",
  we: "mu",
  they: "su",
  me: "ni",
  us: "mu",
  them: "su",
  you: "kai",
  I: "ni",
  myself: "kaina",
  yourself: "kanka",
  himself: "kansa",
  herself: "kanta",
  itself: "kansa",
  ourselves: "kanmu",
  yourselves: "kanku",
  themselves: "kansu",
  who: "wane",
  whom: "wani",
  whose: "nawa",
  which: "wane",
  what: "me",
  someone: "wani",
  anyone: "duk wanda",
  everyone: "duk wanda",
  and: "da",
  but: "amma",
  or: "ko",
  nor: "ko",
  yet: "amma",
  so: "saboda haka",
  however: "duk da haka",
  because: "saboda",
  although: "duk da haka",
  though: "ko da yake",
  since: "tun",
  if: "idan",
  unless: "bari",
  while: "yana",
  whereas: "saboda haka",
  in: "a cikin",
  on: "a kan",
  at: "a",
  by: "ta",
  for: "domin",
  with: "tare da",
  to: "zuwa",
  of: "na",
  as: "kamar",
  between: "a tsakanin",
  through: "ta",
  about: "game da",
  into: "zuwa cikin",
  onto: "zuwa",
  upon: "a kan",
  beside: "a gefen",
  behind: "a baya",
  within: "cikin",
  is: "ne",
  are: "sune",
  was: "ya kasance",
  were: "suna",
  am: "ina",
  be: "kasance",
  being: "kasancewa",
  been: "ya kasance",
  has: "yana da",
  have: "na da",
  had: "yana da",
  do: "yi",
  does: "yana",
  did: "ya yi",
  will: "zai",
  would: "zai",
  shall: "za mu",
  should: "ya kamata",
  can: "zai iya",
  could: "zai iya",
  may: "zai iya",
  might: "zai iya",
  must: "dole",
  here: "a nan",
  there: "a can",
  then: "sai",
  now: "yanzu",
  very: "amma",
  too: "ma",
  always: "kullum",
  never: "ba",
  sometimes: "wasu lokuta",
  often: "yawan",
  seldom: "rare",
  usually: "a al'ada",
  already: "tuni",
  yet: "har yanzu",
  soon: "da wuri",
  late: "jinkiri",
  this: "wannan",
  that: "wannan",
  these: "wadannan",
  those: "wadannan",
  some: "wasu",
  any: "kowane",
  no: "ba",
  all: "duk",
  few: "kaɗan",
  many: "da yawa",
  most: "yafi",
  much: "da yawa",
  such: "kamar",
  each: "kowane",
  every: "kowane",
  both: "dubi",
  either: "ko",
};

const hindi = {
  a: "एक",
  an: "एक",
  the: "वह",
  he: "वह",
  she: "वह",
  it: "यह",
  her: "उसका",
  his: "उसका",
  we: "हम",
  they: "वे",
  me: "मुझे",
  us: "हमें",
  them: "उन्हें",
  you: "तुम",
  I: "मैं",
  myself: "मैं खुद",
  yourself: "तुम खुद",
  himself: "वह खुद",
  herself: "वह खुद",
  itself: "यह खुद",
  ourselves: "हम खुद",
  yourselves: "तुम खुद",
  themselves: "वे खुद",
  who: "कौन",
  whom: "किसे",
  whose: "किसका",
  which: "कौन सा",
  what: "क्या",
  someone: "कोई",
  anyone: "कोई भी",
  everyone: "हर कोई",
  and: "और",
  but: "लेकिन",
  or: "या",
  nor: "न ही",
  yet: "फिर भी",
  so: "इसलिए",
  however: "हालाँकि",
  because: "क्योंकि",
  although: "हालाँकि",
  though: "हालाँकि",
  since: "चूँकि",
  if: "अगर",
  unless: "जब तक",
  while: "जबकि",
  whereas: "जबकि",
  in: "में",
  on: "पर",
  at: "पर",
  by: "द्वारा",
  for: "के लिए",
  with: "साथ",
  to: "को",
  of: "का",
  as: "जैसा",
  between: "के बीच",
  through: "के माध्यम से",
  about: "के बारे में",
  into: "में",
  onto: "पर",
  upon: "पर",
  beside: "के पास",
  behind: "पीछे",
  within: "के भीतर",
  is: "है",
  are: "हैं",
  was: "था",
  were: "थे",
  am: "हूँ",
  be: "होना",
  being: "होना",
  been: "हो चुका",
  has: "है",
  have: "है",
  had: "था",
  do: "करना",
  does: "करता है",
  did: "किया",
  will: "होगा",
  would: "होता",
  shall: "होगा",
  should: "चाहिए",
  can: "सकता है",
  could: "सकता था",
  may: "हो सकता है",
  might: "हो सकता है",
  must: "जरूरी है",
  here: "यहाँ",
  there: "वहाँ",
  then: "तब",
  now: "अब",
  very: "बहुत",
  too: "बहुत",
  always: "हमेशा",
  never: "कभी नहीं",
  sometimes: "कभी-कभी",
  often: "अक्सर",
  seldom: "कभी-कभी",
  usually: "आमतौर पर",
  already: "पहले ही",
  yet: "अभी तक",
  soon: "जल्दी",
  late: "देरी",
  this: "यह",
  that: "वह",
  these: "ये",
  those: "वे",
  some: "कुछ",
  any: "कोई भी",
  no: "नहीं",
  all: "सभी",
  few: "कुछ",
  many: "बहुत",
  most: "अधिकतर",
  much: "बहुत",
  such: "ऐसा",
  each: "प्रत्येक",
  every: "हर",
  both: "दोनों",
  either: "कोई भी",
};

const igbo = {
  a: "otu",
  an: "otu",
  the: "nke",
  he: "ọ",
  she: "ọ",
  it: "ọ",
  her: "ya",
  his: "ya",
  we: "anyị",
  they: "ha",
  me: "m",
  us: "anyi",
  them: "ha",
  you: "ị",
  I: "anyị",
  myself: "m onwe m",
  yourself: "ị onwe gị",
  himself: "ọ onwe ya",
  herself: "ọ onwe ya",
  itself: "ọ onwe ya",
  ourselves: "anyị onwe anyị",
  yourselves: "ị onwe gị",
  themselves: "ha onwe ha",
  who: "onye",
  whom: "onye",
  whose: "nke onye",
  which: "nke",
  what: "gịnị",
  someone: "onye",
  anyone: "onye ọ bụla",
  everyone: "onye ọ bụla",
  and: "na",
  but: "ma",
  or: "ma ọ bụ",
  nor: "ma ọ bụ",
  yet: "nke ahụ",
  so: "ya mere",
  however: "agbanyeghị",
  because: "n'ihi na",
  although: "n'agbanyeghị",
  though: "ma ọ bụ",
  since: "tupu",
  if: "ọ bụrụ",
  unless: "ma ọ bụghị",
  while: "mgbe",
  whereas: "ebe ọ bụ",
  in: "n'ime",
  on: "na",
  at: "na",
  by: "site n'aka",
  for: "maka",
  with: "na",
  to: "na",
  of: "nke",
  as: "dịka",
  between: "n'etiti",
  through: "site n'ụzọ",
  about: "banyere",
  into: "n'ime",
  onto: "na",
  upon: "na",
  beside: "n'akụkụ",
  behind: "n'azụ",
  within: "n'ime",
  is: "bụ",
  are: "bụ",
  was: "bụ",
  were: "bụ",
  am: "bụ",
  be: "bụ",
  being: "bụ",
  been: "bụ",
  has: "enwe",
  have: "enwe",
  had: "enwe",
  do: "mee",
  does: "na-eme",
  did: "mere",
  will: "ga-eme",
  would: "ga-eme",
  shall: "ga-eme",
  should: "ga-eme",
  can: "ikwe",
  could: "ikwe",
  may: "nwere ike",
  might: "nwere ike",
  must: " kwesịrị",
  here: "ebe a",
  there: "ebe ahụ",
  then: "n'ikpeazụ",
  now: "ugbu a",
  very: "ọtụtụ",
  too: "kwa",
  always: "na-adị mgbe niile",
  never: "n'agbanyeghị",
  sometimes: "ọtụtụ mgbe",
  often: "akara",
  seldom: "ụfọdụ",
  usually: "nke a na-eme mgbe niile",
  already: "n'oge gara aga",
  yet: "ka",
  soon: "na-adịghị anya",
  late: "ogologo oge",
  this: "nke a",
  that: "nke ahụ",
  these: "nke ndị a",
  those: "nke ndị ahụ",
  some: "ụfọdụ",
  any: "ọ bụla",
  no: "mba",
  all: "anyị niile",
  few: "ole",
  many: "ọtụtụ",
  most: "kacha",
  much: "ọtụtụ",
  such: "dị ka",
  each: "nke ọ bụla",
  every: "ọ bụla",
  both: "ma abụọ",
  either: "ọ bụ",
};

const indonesia = {
  a: "sebuah",
  an: "sebuah",
  the: "yang",
  he: "dia",
  she: "dia",
  it: "itu",
  her: "dia",
  his: "dia",
  we: "kami",
  they: "mereka",
  me: "saya",
  us: "kami",
  them: "mereka",
  you: "kamu",
  I: "saya",
  myself: "saya sendiri",
  yourself: "kamu sendiri",
  himself: "dia sendiri",
  herself: "dia sendiri",
  itself: "itu sendiri",
  ourselves: "kami sendiri",
  yourselves: "kalian sendiri",
  themselves: "mereka sendiri",
  who: "siapa",
  whom: "siapa",
  whose: "milik siapa",
  which: "yang mana",
  what: "apa",
  someone: "seseorang",
  anyone: "siapa saja",
  everyone: "semua orang",
  and: "dan",
  but: "tetapi",
  or: "atau",
  nor: "atau tidak",
  yet: "tetapi",
  so: "jadi",
  however: "namun",
  because: "karena",
  although: "meskipun",
  though: "meskipun",
  since: "sejak",
  if: "jika",
  unless: "kecuali",
  while: "sementara",
  whereas: "padahal",
  in: "di",
  on: "di atas",
  at: "di",
  by: "oleh",
  for: "untuk",
  with: "dengan",
  to: "ke",
  of: "dari",
  as: "sebagai",
  between: "antara",
  through: "melalui",
  about: "tentang",
  into: "ke dalam",
  onto: "ke atas",
  upon: "pada",
  beside: "di samping",
  behind: "di belakang",
  within: "dalam",
  is: "adalah",
  are: "adalah",
  was: "adalah",
  were: "adalah",
  am: "saya",
  be: "menjadi",
  being: "menjadi",
  been: "telah",
  has: "memiliki",
  have: "memiliki",
  had: "memiliki",
  do: "melakukan",
  does: "melakukan",
  did: "melakukan",
  will: "akan",
  would: "akan",
  shall: "akan",
  should: "seharusnya",
  can: "bisa",
  could: "bisa",
  may: "boleh",
  might: "mungkin",
  must: "harus",
  here: "di sini",
  there: "di sana",
  then: "kemudian",
  now: "sekarang",
  very: "sangat",
  too: "terlalu",
  always: "selalu",
  never: "tidak pernah",
  sometimes: "kadang-kadang",
  often: "sering",
  seldom: "jarang",
  usually: "biasanya",
  already: "sudah",
  yet: "belum",
  soon: "segera",
  late: "terlambat",
  this: "ini",
  that: "itu",
  these: "ini",
  those: "itu",
  some: "beberapa",
  any: "apa saja",
  no: "tidak",
  all: "semua",
  few: "beberapa",
  many: "banyak",
  most: "kebanyakan",
  much: "banyak",
  such: "seperti itu",
  each: "setiap",
  every: "setiap",
  both: "keduanya",
  either: "salah satu",
};

const japanese = {
  a: "一つの",
  an: "一つの",
  the: "その",
  he: "彼",
  she: "彼女",
  it: "それ",
  her: "彼女の",
  his: "彼の",
  we: "私たち",
  they: "彼ら",
  me: "私",
  us: "私たち",
  them: "彼ら",
  you: "あなた",
  I: "私",
  myself: "私自身",
  yourself: "あなた自身",
  himself: "彼自身",
  herself: "彼女自身",
  itself: "それ自身",
  ourselves: "私たち自身",
  yourselves: "あなたたち自身",
  themselves: "彼ら自身",
  who: "誰",
  whom: "誰を",
  whose: "誰の",
  which: "どれ",
  what: "何",
  someone: "誰か",
  anyone: "誰でも",
  everyone: "皆",
  and: "そして",
  but: "しかし",
  or: "または",
  nor: "または",
  yet: "まだ",
  so: "だから",
  however: "しかしながら",
  because: "なぜなら",
  although: "にもかかわらず",
  though: "けれども",
  since: "〜以来",
  if: "もし",
  unless: "もし〜でなければ",
  while: "〜の間",
  whereas: "〜であるのに対して",
  in: "中で",
  on: "上に",
  at: "で",
  by: "〜によって",
  for: "ために",
  with: "〜と一緒に",
  to: "〜に",
  of: "の",
  as: "として",
  between: "間に",
  through: "通して",
  about: "について",
  into: "〜の中に",
  onto: "〜の上に",
  upon: "〜の上に",
  beside: "〜のそばに",
  behind: "後ろに",
  within: "中に",
  is: "です",
  are: "です",
  was: "でした",
  were: "でした",
  am: "です",
  be: "〜である",
  being: "存在している",
  been: "〜であった",
  has: "持っています",
  have: "持っています",
  had: "持っていました",
  do: "する",
  does: "します",
  did: "しました",
  will: "〜するつもりです",
  would: "〜するだろう",
  shall: "〜しよう",
  should: "〜すべきです",
  can: "できる",
  could: "できた",
  may: "かもしれません",
  might: "かもしれません",
  must: "〜しなければならない",
  here: "ここ",
  there: "そこ",
  then: "その時",
  now: "今",
  very: "とても",
  too: "あまりに",
  always: "いつも",
  never: "決して",
  sometimes: "時々",
  often: "しばしば",
  seldom: "めったに",
  usually: "通常",
  already: "すでに",
  yet: "まだ",
  soon: "すぐに",
  late: "遅く",
  this: "これ",
  that: "それ",
  these: "これら",
  those: "それら",
  some: "いくつかの",
  any: "どんな",
  no: "ない",
  all: "すべて",
  few: "少数の",
  many: "多くの",
  most: "最も",
  much: "多くの",
  such: "そのような",
  each: "それぞれの",
  every: "すべての",
  both: "両方",
  either: "どちらか",
};

const korean = {
  a: "하나의",
  an: "하나의",
  the: "그",
  he: "그",
  she: "그녀",
  it: "그것",
  her: "그녀의",
  his: "그의",
  we: "우리",
  they: "그들",
  me: "나를",
  us: "우리",
  them: "그들",
  you: "너",
  I: "나",
  myself: "나 자신",
  yourself: "너 자신",
  himself: "그 자신",
  herself: "그녀 자신",
  itself: "그것 자체",
  ourselves: "우리 자신",
  yourselves: "너희들 자신",
  themselves: "그들 자신",
  who: "누구",
  whom: "누구를",
  whose: "누구의",
  which: "어느",
  what: "무엇",
  someone: "누군가",
  anyone: "누구든지",
  everyone: "모든 사람",
  and: "그리고",
  but: "하지만",
  or: "또는",
  nor: "아니면",
  yet: "하지만",
  so: "그래서",
  however: "하지만",
  because: "왜냐하면",
  although: "비록 ~일지라도",
  though: "그렇지만",
  since: "이후",
  if: "만약",
  unless: "만약 ~이 아니라면",
  while: "~동안",
  whereas: "~인 반면",
  in: "안에",
  on: "위에",
  at: "에서",
  by: "~에 의해서",
  for: "~을 위해",
  with: "~와 함께",
  to: "~에게",
  of: "~의",
  as: "~처럼",
  between: "~사이에",
  through: "~을 통해",
  about: "~에 대해",
  into: "~로",
  onto: "~위로",
  upon: "~위에",
  beside: "~옆에",
  behind: "~뒤에",
  within: "~안에",
  is: "이다",
  are: "이다",
  was: "이었다",
  were: "였다",
  am: "이다",
  be: "이다",
  being: "있는",
  been: "이었다",
  has: "가지고 있다",
  have: "가지고 있다",
  had: "가졌다",
  do: "하다",
  does: "한다",
  did: "했다",
  will: "~할 것이다",
  would: "~할 것이다",
  shall: "~할 것이다",
  should: "~해야 한다",
  can: "할 수 있다",
  could: "할 수 있었다",
  may: "~일 수 있다",
  might: "~일 수 있다",
  must: "~해야 한다",
  here: "여기",
  there: "저기",
  then: "그때",
  now: "지금",
  very: "매우",
  too: "너무",
  always: "항상",
  never: "결코",
  sometimes: "가끔",
  often: "자주",
  seldom: "드물게",
  usually: "보통",
  already: "이미",
  yet: "아직",
  soon: "곧",
  late: "늦은",
  this: "이",
  that: "저",
  these: "이것들",
  those: "저것들",
  some: "일부",
  any: "어떤",
  no: "아니",
  all: "모든",
  few: "몇몇",
  many: "많은",
  most: "대부분",
  much: "많은",
  such: "그러한",
  each: "각각의",
  every: "모든",
  both: "양쪽의",
  either: "어느 하나",
};

const kyrgyz = {
  a: "бир",
  an: "бир",
  the: "анын",
  he: "ал",
  she: "ал",
  it: "ал",
  her: "анын",
  his: "анын",
  we: "биз",
  they: "алар",
  me: "мен",
  us: "бизди",
  them: "аларды",
  you: "сен",
  I: "мен",
  myself: "өзүм",
  yourself: "өзүң",
  himself: "өзү",
  herself: "өзү",
  itself: "өзү",
  ourselves: "өзүбүз",
  yourselves: "өзүңөр",
  themselves: "өздөрү",
  who: "кто",
  whom: "кимге",
  whose: "кимдин",
  which: "кайсы",
  what: "не",
  someone: "бирөө",
  anyone: "күчтүү",
  everyone: "ар бир адам",
  and: "жана",
  but: "бирок",
  or: "же",
  nor: "жок",
  yet: "деп жатам",
  so: "ошондуктан",
  however: "бирок",
  because: "күнү",
  although: "алегиче",
  though: "бирок",
  since: "эми",
  if: "эгер",
  unless: "эгерде",
  while: "кезинде",
  whereas: "ошол сыяктуу",
  in: "ичинде",
  on: "үстүндө",
  at: "биздин",
  by: "аркасында",
  for: "үчүн",
  with: "менен",
  to: "көнүл буруу",
  of: "негизинде",
  as: "жакшы",
  between: "арасында",
  through: "барыш",
  about: "түшүнүү",
  into: "ичине",
  onto: "жерге",
  upon: "чогултуу",
  beside: "жанында",
  behind: "артыңда",
  within: "ичинде",
  is: "боло",
  are: "билинүү",
  was: "болгон",
  were: "болгон",
  am: "мындан",
  be: "болууга",
  being: "болуу",
  been: "болгон",
  has: "бар",
  have: "бар",
  had: "бар болчу",
  do: "иштөө",
  does: "жасайт",
  did: "жасады",
  will: "болот",
  would: "болушу",
  shall: "болушу",
  should: "жасашы керек",
  can: "кана",
  could: "болот",
  may: "мүмкүн",
  might: "болушу мүмкүн",
  must: "катар",
  here: "бул жерде",
  there: "анда",
  then: "ошондо",
  now: "азыр",
  very: "жана",
  too: "жана",
  always: "ар дайым",
  never: "кечиресиз",
  sometimes: "кээде",
  often: "көп",
  seldom: "сирек",
  usually: "адатта",
  already: "алдын ала",
  yet: "жана",
  soon: "көп өтпөй",
  late: "кеч",
  this: "бул",
  that: "ошол",
  these: "булар",
  those: "алар",
  some: "кээде",
  any: "көп",
  no: "жок",
  all: "бардык",
  few: "аз",
  many: "көп",
  most: "көпчүлүгү",
  much: "көп",
  such: "ушул",
  each: "күчтүү",
  every: "ар бир",
  both: "экөө",
  either: "же",
};

const marathi = {
  a: "एक",
  an: "एक",
  the: "तो|ती|ते",
  he: "तो",
  she: "ती",
  it: "हे",
  her: "तिचं",
  his: "त्याचं",
  we: "आम्ही",
  they: "ते",
  me: "माझं",
  us: "आम्हाला",
  them: "त्यांना",
  you: "तुम्ही",
  I: "मी",
  myself: "स्वतः",
  yourself: "तुम्ही स्वतः",
  himself: "तो स्वतः",
  herself: "ती स्वतः",
  itself: "हे स्वतः",
  ourselves: "आम्ही स्वतः",
  yourselves: "तुम्ही स्वतः",
  themselves: "ते स्वतः",
  who: "कोण",
  whom: "कोणाला",
  whose: "कसला",
  which: "काय",
  what: "कसला",
  someone: "कोणी",
  anyone: "कोणीही",
  everyone: "सर्व",
  and: "आणि",
  but: "पण",
  or: "किंवा",
  nor: "नाही",
  yet: "तरीही",
  so: "म्हणून",
  however: "तरीही",
  because: "कारण",
  although: "जरी",
  though: "तरीही",
  since: "तपासल्यापासून",
  if: "जर",
  unless: "जर नाही",
  while: "जेव्हा",
  whereas: "परंतु",
  in: "मध्ये",
  on: "वर",
  at: "येथे",
  by: "द्वारे",
  for: "साठी",
  with: "सह",
  to: "कडे",
  of: "चे",
  as: "सारखा",
  between: "मध्ये",
  through: "मार्गे",
  about: "बद्दल",
  into: "मध्ये",
  onto: "वर",
  upon: "वर",
  beside: "जवळ",
  behind: "मागे",
  within: "आत",
  is: "आहे",
  are: "आहेत",
  was: "होता",
  were: "होते",
  am: "आहे",
  be: "असणे",
  being: "असणे",
  been: "होता",
  has: "आहे",
  have: "आहे",
  had: "होता",
  do: "करा",
  does: "करतो",
  did: "केलं",
  will: "हव",
  would: "होईल",
  shall: "शक्य",
  should: "पाहिजे",
  can: "सकता",
  could: "सकला",
  may: "होऊ शकते",
  might: "होऊ शकते",
  must: "असावे",
  here: "इथे",
  there: "तेथे",
  then: "तेव्हा",
  now: "आता",
  very: "खूप",
  too: "खूप",
  always: "नेहमी",
  never: "कधीच नाही",
  sometimes: "कधी कधी",
  often: "सर्वसाधारणपणे",
  seldom: "कधीच नाही",
  usually: "साधारणपणे",
  already: "आधीच",
  yet: "आतापर्यंत",
  soon: "लवकरच",
  late: "उशीर",
  this: "हे",
  that: "तो",
  these: "हे",
  those: "ते",
  some: "काही",
  any: "काही",
  no: "नाही",
  all: "सर्व",
  few: "काही",
  many: "बरेच",
  most: "बहुतेक",
  much: "खूप",
  such: "अशा",
  each: "प्रत्येक",
  every: "प्रत्येक",
  both: "दोन्ही",
  either: "किंवा",
};

const mundo = {
  a: "un|una",
  an: "un|una",
  the: "el|la|los|las",
  he: "él",
  she: "ella",
  it: "lo|la",
  her: "su|la",
  his: "su",
  we: "nosotros|nosotras",
  they: "ellos|ellas",
  me: "me",
  us: "nos",
  them: "los|las",
  you: "tú|usted|vosotros|vosotras",
  I: "yo",
  myself: "yo mismo|yo misma",
  yourself: "tú mismo|tú misma",
  himself: "él mismo",
  herself: "ella misma",
  itself: "eso mismo",
  ourselves: "nosotros mismos|nosotras mismas",
  yourselves: "vosotros mismos|vosotras mismas",
  themselves: "ellos mismos|ellas mismas",
  who: "quién",
  whom: "a quién",
  whose: "cuyo|cuya|cuyos|cuyas",
  which: "cuál|qué",
  what: "qué",
  someone: "alguien",
  anyone: "cualquiera",
  everyone: "todos|todas",
  and: "y",
  but: "pero",
  or: "o",
  nor: "ni",
  yet: "sin embargo",
  so: "así que",
  however: "sin embargo",
  because: "porque",
  although: "aunque",
  though: "aunque",
  since: "desde",
  if: "si",
  unless: "a menos que",
  while: "mientras",
  whereas: "mientras que",
  in: "en",
  on: "en|sobre",
  at: "en|a",
  by: "por|junto a",
  for: "para",
  with: "con",
  to: "a",
  of: "de",
  as: "como",
  between: "entre",
  through: "a través de",
  about: "acerca de|sobre",
  into: "en",
  onto: "sobre",
  upon: "sobre",
  beside: "junto a",
  behind: "detrás de",
  within: "dentro de",
  is: "es",
  are: "son|están",
  was: "era|estaba",
  were: "eran|estaban",
  am: "soy|estoy",
  be: "ser|estar",
  being: "siendo|estando",
  been: "sido|estado",
  has: "ha",
  have: "tengo|ha",
  had: "tuve|había",
  do: "hacer",
  does: "hace",
  did: "hizo",
  will: "será|hará",
  would: "haría",
  shall: "debería",
  should: "debería",
  can: "puede",
  could: "podría",
  may: "puede|quizá",
  might: "podría",
  must: "debe",
  here: "aquí",
  there: "allí|ahí",
  then: "entonces",
  now: "ahora",
  very: "muy",
  too: "demasiado",
  always: "siempre",
  never: "nunca",
  sometimes: "a veces",
  often: "a menudo",
  seldom: "raramente",
  usually: "usualmente",
  already: "ya",
  yet: "aún",
  soon: "pronto",
  late: "tarde",
  this: "esto|esta|este",
  that: "ese|esa|eso",
  these: "estos|estas",
  those: "esos|esas",
  some: "alguno|alguna",
  any: "cualquier",
  no: "no",
  all: "todos|todas",
  few: "pocos|pocas",
  many: "muchos|muchas",
  most: "la mayoría",
  much: "mucho",
  such: "tal",
  each: "cada",
  every: "cada",
  both: "ambos|ambas",
  either: "cualquiera",
};

const naidheachdan = {
  a: "aon",
  an: "an",
  the: "an|am",
  he: "e",
  she: "i",
  it: "e|i",
  her: "aice",
  his: "a",
  we: "sinn",
  they: "iad",
  me: "mi",
  us: "sinn",
  them: "iad",
  you: "thu|sibh",
  I: "mi",
  myself: "mi fhìn",
  yourself: "thu fhìn",
  himself: "e fhèin",
  herself: "i fhèin",
  itself: "e fhèin|i fhèin",
  ourselves: "sinn fhìn",
  yourselves: "sibh fhìn",
  themselves: "iad fhìn",
  who: "dè",
  whom: "dè an t-uasal",
  whose: "cò tha aige|cò tha aice",
  which: "dè",
  what: "dè",
  someone: "duine",
  anyone: "duine sam bith",
  everyone: "gach duine",
  and: "agus",
  but: "ach",
  or: "no",
  nor: "no",
  yet: "fhathast",
  so: "mar sin",
  however: "ach",
  because: "air sgàth",
  although: "ged",
  though: "ged",
  since: "bhon",
  if: "ma",
  unless: "mura",
  while: "fhad ‘s a bhios",
  whereas: "fhad ‘s a bhios",
  in: "ann an",
  on: "air",
  at: "aig",
  by: "le",
  for: "airson",
  with: "le",
  to: "gu",
  of: "de",
  as: "mar",
  between: "eadar",
  through: "tro",
  about: "mu",
  into: "a-steach",
  onto: "air",
  upon: "air",
  beside: "ri taobh",
  behind: "air cùl",
  within: "ann an",
  is: "tha",
  are: "tha",
  was: "bha",
  were: "bha",
  am: "tha",
  be: "a bhith",
  being: "a bhith",
  been: "bha",
  has: "tha",
  have: "tha",
  had: "bha",
  do: "dèanamh",
  does: "dèanamh",
  did: "rinn",
  will: "bheir",
  would: "bheireadh",
  shall: "bu chòir",
  should: "bu chòir",
  can: "faod",
  could: "b’ urrainn",
  may: "faod",
  might: "b’ urrainn",
  must: "feumaidh",
  here: "an seo",
  there: "an sin",
  then: "an uair sin",
  now: "a-nis",
  very: "mòr",
  too: "ro",
  always: "an-còmhnaidh",
  never: "a-riamh",
  sometimes: "uaireannan",
  often: "gu tric",
  seldom: "gu slaodach",
  usually: "mar as trice",
  already: "mu thràth",
  yet: "fhathast",
  soon: "a dh’aithghearr",
  late: "duilich",
  this: "seo",
  that: "sin",
  these: "na",
  those: "sin",
  some: "beagan",
  any: "sam bith",
  no: "chan eil",
  all: "gach",
  few: "beagan",
  many: "mòran",
  most: "am mòran",
  much: "mòran",
  such: "mar sin",
  each: "gach",
  every: "gach",
  both: "an dithis",
  either: "sam bith",
};

const nepali = {
  a: "एक",
  an: "एक",
  the: "यो",
  he: "उहाँ",
  she: "उहाँ",
  it: "यो",
  her: "उहाँको",
  his: "उहाँको",
  we: "हामी",
  they: "उनीहरू",
  me: "म",
  us: "हामीलाई",
  them: "उनीहरूलाई",
  you: "तिमी",
  I: "म",
  myself: "म आफै",
  yourself: "तिमी आफै",
  himself: "उहाँ आफै",
  herself: "उहाँ आफै",
  itself: "यो आफै",
  ourselves: "हामी आफै",
  yourselves: "तिमीहरू आफै",
  themselves: "उनीहरू आफै",
  who: "को",
  whom: "कसलाई",
  whose: "कसको",
  which: "कुन",
  what: "के",
  someone: "कसै",
  anyone: "कसैलाई",
  everyone: "सबैलाई",
  and: "र",
  but: "तर",
  or: "वा",
  nor: "न त",
  yet: "अझै",
  so: "त्यसैले",
  however: "यद्यपि",
  because: "किनभने",
  although: "यद्यपि",
  though: "यद्यपि",
  since: "देखि",
  if: "यदि",
  unless: "नत्र",
  while: "जब",
  whereas: "जहाँ",
  in: "मा",
  on: "मा",
  at: "मा",
  by: "द्वारा",
  for: "को लागि",
  with: "संग",
  to: "लाई",
  of: "को",
  as: "जस्तै",
  between: "बीच",
  through: "मार्फत",
  about: "बारेमा",
  into: "मा",
  onto: "मा",
  upon: "मा",
  beside: "छेउमा",
  behind: "पछि",
  within: "भित्र",
  is: "हो",
  are: "छन्",
  was: "थियो",
  were: "थिए",
  am: "छु",
  be: "हुनु",
  being: "हुदै",
  been: "भएको",
  has: "छ",
  have: "छ",
  had: "थियो",
  do: "गर्नु",
  does: "गर्छ",
  did: "गरेको",
  will: "गर्नेछ",
  would: "गर्नेछ",
  shall: "गर्नेछ",
  should: "गर्नु पर्छ",
  can: "सक्छ",
  could: "सक्थ्यो",
  may: "सक्छ",
  might: "सक्छ",
  must: "पर्छ",
  here: "यहाँ",
  there: "त्यहाँ",
  then: "त्यसपछि",
  now: "अहिले",
  very: "धेरै",
  too: "पनि",
  always: "सधैं",
  never: "कहिल्यै",
  sometimes: "कहिलेकाहीं",
  often: "धेरै जसो",
  seldom: "कहिलेकाहीं",
  usually: "सामान्यतया",
  already: "पहिले नै",
  yet: "अझै",
  soon: "छिट्टै",
  late: "ढिलो",
  this: "यो",
  that: "त्यो",
  these: "यी",
  those: "ती",
  some: "केही",
  any: "कुनै",
  no: "होइन",
  all: "सबै",
  few: "केही",
  many: "धेरै",
  most: "धेरै",
  much: "धेरै",
  such: "यस्तो",
  each: "प्रत्येक",
  every: "हरेक",
  both: "दुवै",
  either: "कुनै एक",
};

const pashto = {
  a: "يو",
  an: "يو",
  the: "دا",
  he: "هغه",
  she: "هغې",
  it: "دا",
  her: "د هغې",
  his: "د هغه",
  we: "موږ",
  they: "هغوی",
  me: "زه",
  us: "موږ",
  them: "هغوی",
  you: "تاسو",
  I: "زه",
  myself: "زه پخپله",
  yourself: "تاسو پخپله",
  himself: "هغه پخپله",
  herself: "هغې پخپله",
  itself: "دا پخپله",
  ourselves: "موږ پخپله",
  yourselves: "تاسو پخپله",
  themselves: "هغوی پخپله",
  who: "څوک",
  whom: "څوک",
  whose: "د چا",
  which: "کوم",
  what: "څه",
  someone: "څوک",
  anyone: "هر څوک",
  everyone: "هر څوک",
  and: "او",
  but: "خو",
  or: "يا",
  nor: "نه",
  yet: "لا",
  so: "نو",
  however: "خو",
  because: "ځکه چې",
  although: "که څه هم",
  though: "که څه هم",
  since: "له هغه وخت راهیسې",
  if: "که",
  unless: "مګر که",
  while: "پداسې حال کې چې",
  whereas: "پداسې حال کې چې",
  in: "په",
  on: "په",
  at: "په",
  by: "له خوا",
  for: "لپاره",
  with: "سره",
  to: "ته",
  of: "د",
  as: "لکه",
  between: "تر منځ",
  through: "له لارې",
  about: "په اړه",
  into: "ته",
  onto: "ته",
  upon: "باندې",
  beside: "تر څنګ",
  behind: "شاته",
  within: "دننه",
  is: "دی",
  are: "دي",
  was: "و",
  were: "وو",
  am: "يم",
  be: "وي",
  being: "کېدل",
  been: "شوی",
  has: "لري",
  have: "لري",
  had: "لرله",
  do: "کوي",
  does: "کوي",
  did: "کړل",
  will: "به",
  would: "به",
  shall: "به",
  should: "پکار دی",
  can: "کولی شي",
  could: "کولی شو",
  may: "کیدای شي",
  might: "کیدای شي",
  must: "پکار دی",
  here: "دلته",
  there: "هلته",
  then: "بیا",
  now: "اوس",
  very: "ډیر",
  too: "هم",
  always: "تل",
  never: "هیڅکله",
  sometimes: "کله ناکله",
  often: "اکثره",
  seldom: "ډیر لږ",
  usually: "معمولا",
  already: "لا دمخه",
  yet: "لا",
  soon: "ژر",
  late: "ناوخته",
  this: "دا",
  that: "هغه",
  these: "دا",
  those: "هغه",
  some: "ځینې",
  any: "هر",
  no: "نه",
  all: "ټول",
  few: "څو",
  many: "ډیر",
  most: "ډیر",
  much: "ډیر",
  such: "لکه",
  each: "هر یو",
  every: "هر",
  both: "دواړه",
  either: "یا",
};

const persian = {
  a: "یک",
  an: "یک",
  the: "این",
  he: "او",
  she: "او",
  it: "آن",
  her: "او",
  his: "او",
  we: "ما",
  they: "آنها",
  me: "من",
  us: "ما",
  them: "آنها",
  you: "تو",
  I: "من",
  myself: "خودم",
  yourself: "خودت",
  himself: "خودش",
  herself: "خودش",
  itself: "خودش",
  ourselves: "خودمان",
  yourselves: "خودتان",
  themselves: "خودشان",
  who: "چه کسی",
  whom: "چه کسی",
  whose: "مال چه کسی",
  which: "کدام",
  what: "چه",
  someone: "کسی",
  anyone: "هر کسی",
  everyone: "همه",
  and: "و",
  but: "اما",
  or: "یا",
  nor: "نه",
  yet: "هنوز",
  so: "بنابراین",
  however: "با این حال",
  because: "زیرا",
  although: "اگرچه",
  though: "اگرچه",
  since: "از آنجا که",
  if: "اگر",
  unless: "مگر اینکه",
  while: "در حالی که",
  whereas: "در حالی که",
  in: "در",
  on: "روی",
  at: "در",
  by: "توسط",
  for: "برای",
  with: "با",
  to: "به",
  of: "از",
  as: "به عنوان",
  between: "بین",
  through: "از طریق",
  about: "درباره",
  into: "به",
  onto: "روی",
  upon: "بر",
  beside: "کنار",
  behind: "پشت",
  within: "در داخل",
  is: "است",
  are: "هستند",
  was: "بود",
  were: "بودند",
  am: "هستم",
  be: "بودن",
  being: "بودن",
  been: "بوده",
  has: "دارد",
  have: "دارند",
  had: "داشت",
  do: "انجام دادن",
  does: "انجام می دهد",
  did: "انجام داد",
  will: "خواهد",
  would: "می خواهد",
  shall: "باید",
  should: "باید",
  can: "می تواند",
  could: "می توانست",
  may: "ممکن است",
  might: "ممکن است",
  must: "باید",
  here: "اینجا",
  there: "آنجا",
  then: "سپس",
  now: "اکنون",
  very: "بسیار",
  too: "خیلی",
  always: "همیشه",
  never: "هرگز",
  sometimes: "گاهی",
  often: "اغلب",
  seldom: "به ندرت",
  usually: "معمولاً",
  already: "قبلاً",
  yet: "هنوز",
  soon: "به زودی",
  late: "دیر",
  this: "این",
  that: "آن",
  these: "اینها",
  those: "آنها",
  some: "برخی",
  any: "هر",
  no: "نه",
  all: "همه",
  few: "چند",
  many: "بسیاری",
  most: "اکثر",
  much: "زیاد",
  such: "چنین",
  each: "هر",
  every: "هر",
  both: "هر دو",
  either: "یا",
};

const pidgin = {
  a: "wan",
  an: "wan",
  the: "di",
  he: "im",
  she: "im",
  it: "am",
  her: "her",
  his: "im own",
  we: "we",
  they: "dem",
  me: "me",
  us: "us",
  them: "dem",
  you: "you",
  I: "I",
  myself: "myself",
  yourself: "yourself",
  himself: "imself",
  herself: "herself",
  itself: "itself",
  ourselves: "ourselves",
  yourselves: "yourselves",
  themselves: "themselves",
  who: "who",
  whom: "who",
  whose: "whose",
  which: "which",
  what: "wetin",
  someone: "somebody",
  anyone: "anybody",
  everyone: "everybody",
  and: "and",
  but: "but",
  or: "or",
  nor: "nor",
  yet: "yet",
  so: "so",
  however: "however",
  because: "because",
  although: "although",
  though: "though",
  since: "since",
  if: "if",
  unless: "unless",
  while: "while",
  whereas: "whereas",
  in: "for",
  on: "on top",
  at: "for",
  by: "by",
  for: "for",
  with: "with",
  to: "to",
  of: "of",
  as: "as",
  between: "between",
  through: "through",
  about: "about",
  into: "into",
  onto: "onto",
  upon: "upon",
  beside: "beside",
  behind: "behind",
  within: "within",
  is: "dey",
  are: "dey",
  was: "bin dey",
  were: "bin dey",
  am: "dey",
  be: "be",
  being: "dey",
  been: "don dey",
  has: "get",
  have: "get",
  had: "get",
  do: "do",
  does: "do",
  did: "do",
  will: "go",
  would: "go",
  shall: "go",
  should: "suppose",
  can: "fit",
  could: "fit",
  may: "fit",
  might: "fit",
  must: "must",
  here: "here",
  there: "there",
  then: "then",
  now: "now",
  very: "very",
  too: "too",
  always: "always",
  never: "never",
  sometimes: "sometimes",
  often: "often",
  seldom: "seldom",
  usually: "usually",
  already: "already",
  yet: "yet",
  soon: "soon",
  late: "late",
  this: "this",
  that: "that",
  these: "these",
  those: "those",
  some: "some",
  any: "any",
  no: "no",
  all: "all",
  few: "few",
  many: "many",
  most: "most",
  much: "much",
  such: "such",
  each: "each",
  every: "every",
  both: "both",
  either: "either",
};

const portuguese = {
  a: "um",
  an: "um",
  the: "o",
  he: "ele",
  she: "ela",
  it: "isso",
  her: "dela",
  his: "dele",
  we: "nós",
  they: "eles",
  me: "me",
  us: "nos",
  them: "eles",
  you: "você",
  I: "eu",
  myself: "eu mesmo",
  yourself: "você mesmo",
  himself: "ele mesmo",
  herself: "ela mesma",
  itself: "isso mesmo",
  ourselves: "nós mesmos",
  yourselves: "vocês mesmos",
  themselves: "eles mesmos",
  who: "quem",
  whom: "quem",
  whose: "cujo",
  which: "qual",
  what: "o que",
  someone: "alguém",
  anyone: "qualquer um",
  everyone: "todos",
  and: "e",
  but: "mas",
  or: "ou",
  nor: "nem",
  yet: "ainda",
  so: "então",
  however: "no entanto",
  because: "porque",
  although: "embora",
  though: "embora",
  since: "desde",
  if: "se",
  unless: "a menos que",
  while: "enquanto",
  whereas: "enquanto",
  in: "em",
  on: "em",
  at: "em",
  by: "por",
  for: "para",
  with: "com",
  to: "para",
  of: "de",
  as: "como",
  between: "entre",
  through: "através",
  about: "sobre",
  into: "em",
  onto: "em",
  upon: "sobre",
  beside: "ao lado",
  behind: "atrás",
  within: "dentro",
  is: "é",
  are: "são",
  was: "era",
  were: "eram",
  am: "sou",
  be: "ser",
  being: "sendo",
  been: "sido",
  has: "tem",
  have: "tem",
  had: "tinha",
  do: "fazer",
  does: "faz",
  did: "fez",
  will: "vai",
  would: "iria",
  shall: "deverá",
  should: "deveria",
  can: "pode",
  could: "poderia",
  may: "pode",
  might: "poderia",
  must: "deve",
  here: "aqui",
  there: "lá",
  then: "então",
  now: "agora",
  very: "muito",
  too: "demais",
  always: "sempre",
  never: "nunca",
  sometimes: "às vezes",
  often: "frequentemente",
  seldom: "raramente",
  usually: "geralmente",
  already: "já",
  yet: "ainda",
  soon: "em breve",
  late: "tarde",
  this: "este",
  that: "aquele",
  these: "estes",
  those: "aqueles",
  some: "alguns",
  any: "qualquer",
  no: "não",
  all: "todos",
  few: "poucos",
  many: "muitos",
  most: "a maioria",
  much: "muito",
  such: "tal",
  each: "cada",
  every: "cada",
  both: "ambos",
  either: "qualquer",
};

const punjabi = {
  a: "ਇੱਕ",
  an: "ਇੱਕ",
  the: "ਇਹ",
  he: "ਉਹ",
  she: "ਉਹ",
  it: "ਇਹ",
  her: "ਉਸਦਾ",
  his: "ਉਸਦਾ",
  we: "ਅਸੀਂ",
  they: "ਉਹ",
  me: "ਮੈਂ",
  us: "ਸਾਨੂੰ",
  them: "ਉਹਨਾਂ ਨੂੰ",
  you: "ਤੁਸੀਂ",
  I: "ਮੈਂ",
  myself: "ਮੈਂ ਖੁਦ",
  yourself: "ਤੁਸੀਂ ਖੁਦ",
  himself: "ਉਹ ਖੁਦ",
  herself: "ਉਹ ਖੁਦ",
  itself: "ਇਹ ਖੁਦ",
  ourselves: "ਅਸੀਂ ਖੁਦ",
  yourselves: "ਤੁਸੀਂ ਖੁਦ",
  themselves: "ਉਹ ਖੁਦ",
  who: "ਕੌਣ",
  whom: "ਕਿਸ ਨੂੰ",
  whose: "ਕਿਸ ਦਾ",
  which: "ਕਿਹੜਾ",
  what: "ਕੀ",
  someone: "ਕੋਈ",
  anyone: "ਕੋਈ ਵੀ",
  everyone: "ਹਰ ਕੋਈ",
  and: "ਅਤੇ",
  but: "ਪਰ",
  or: "ਜਾਂ",
  nor: "ਨਾ ਹੀ",
  yet: "ਅਜੇ ਤੱਕ",
  so: "ਇਸ ਲਈ",
  however: "ਹਾਲਾਂਕਿ",
  because: "ਕਿਉਂਕਿ",
  although: "ਹਾਲਾਂਕਿ",
  though: "ਹਾਲਾਂਕਿ",
  since: "ਜਦੋਂ ਤੋਂ",
  if: "ਜੇ",
  unless: "ਜਦ ਤੱਕ",
  while: "ਜਦੋਂ",
  whereas: "ਜਦਕਿ",
  in: "ਵਿੱਚ",
  on: "ਉੱਤੇ",
  at: "ਤੇ",
  by: "ਦੁਆਰਾ",
  for: "ਲਈ",
  with: "ਨਾਲ",
  to: "ਨੂੰ",
  of: "ਦਾ",
  as: "ਵਜੋਂ",
  between: "ਵਿੱਚ",
  through: "ਰਾਹੀਂ",
  about: "ਬਾਰੇ",
  into: "ਵਿੱਚ",
  onto: "ਉੱਤੇ",
  upon: "ਉੱਤੇ",
  beside: "ਨਾਲ",
  behind: "ਪਿੱਛੇ",
  within: "ਅੰਦਰ",
  is: "ਹੈ",
  are: "ਹਨ",
  was: "ਸੀ",
  were: "ਸਨ",
  am: "ਹਾਂ",
  be: "ਹੋਣਾ",
  being: "ਹੋ ਰਿਹਾ ਹੈ",
  been: "ਹੋ ਚੁੱਕਾ ਹੈ",
  has: "ਹੈ",
  have: "ਹਨ",
  had: "ਸੀ",
  do: "ਕਰਨਾ",
  does: "ਕਰਦਾ ਹੈ",
  did: "ਕੀਤਾ",
  will: "ਕਰੇਗਾ",
  would: "ਕਰੇਗਾ",
  shall: "ਕਰੇਗਾ",
  should: "ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ",
  can: "ਕਰ ਸਕਦਾ ਹੈ",
  could: "ਕਰ ਸਕਦਾ ਸੀ",
  may: "ਹੋ ਸਕਦਾ ਹੈ",
  might: "ਹੋ ਸਕਦਾ ਹੈ",
  must: "ਲਾਜ਼ਮੀ ਹੈ",
  here: "ਇੱਥੇ",
  there: "ਉੱਥੇ",
  then: "ਫਿਰ",
  now: "ਹੁਣ",
  very: "ਬਹੁਤ",
  too: "ਵੀ",
  always: "ਹਮੇਸ਼ਾ",
  never: "ਕਦੇ ਨਹੀਂ",
  sometimes: "ਕਦੇ ਕਦੇ",
  often: "ਅਕਸਰ",
  seldom: "ਕਦਾਚਿਤ",
  usually: "ਅਕਸਰ",
  already: "ਪਹਿਲਾਂ ਹੀ",
  yet: "ਅਜੇ ਤੱਕ",
  soon: "ਜਲਦੀ",
  late: "ਦੇਰ",
  this: "ਇਹ",
  that: "ਉਹ",
  these: "ਇਹਨਾਂ",
  those: "ਉਹਨਾਂ",
  some: "ਕੁਝ",
  any: "ਕੋਈ ਵੀ",
  no: "ਨਹੀਂ",
  all: "ਸਾਰੇ",
  few: "ਕੁਝ",
  many: "ਬਹੁਤ",
  most: "ਜ਼ਿਆਦਾਤਰ",
  much: "ਬਹੁਤ",
  such: "ਇਸ ਤਰ੍ਹਾਂ",
  each: "ਹਰ ਇੱਕ",
  every: "ਹਰ",
  both: "ਦੋਵੇਂ",
  either: "ਕੋਈ ਇੱਕ",
};

const russian = {
  a: "один",
  an: "один",
  the: "этот",
  he: "он",
  she: "она",
  it: "оно",
  her: "её",
  his: "его",
  we: "мы",
  they: "они",
  me: "меня",
  us: "нас",
  them: "их",
  you: "ты",
  I: "я",
  myself: "себя",
  yourself: "себя",
  himself: "себя",
  herself: "себя",
  itself: "себя",
  ourselves: "себя",
  yourselves: "себя",
  themselves: "себя",
  who: "кто",
  whom: "кого",
  whose: "чей",
  which: "который",
  what: "что",
  someone: "кто-то",
  anyone: "кто угодно",
  everyone: "все",
  and: "и",
  but: "но",
  or: "или",
  nor: "ни",
  yet: "ещё",
  so: "так",
  however: "однако",
  because: "потому что",
  although: "хотя",
  though: "хотя",
  since: "с тех пор как",
  if: "если",
  unless: "если не",
  while: "пока",
  whereas: "тогда как",
  in: "в",
  on: "на",
  at: "в",
  by: "по",
  for: "для",
  with: "с",
  to: "к",
  of: "из",
  as: "как",
  between: "между",
  through: "через",
  about: "о",
  into: "в",
  onto: "на",
  upon: "на",
  beside: "рядом",
  behind: "за",
  within: "внутри",
  is: "есть",
  are: "есть",
  was: "был",
  were: "были",
  am: "есть",
  be: "быть",
  being: "быть",
  been: "был",
  has: "имеет",
  have: "имеют",
  had: "имел",
  do: "делать",
  does: "делает",
  did: "делал",
  will: "будет",
  would: "бы",
  shall: "должен",
  should: "должен",
  can: "может",
  could: "мог",
  may: "может",
  might: "мог бы",
  must: "должен",
  here: "здесь",
  there: "там",
  then: "тогда",
  now: "сейчас",
  very: "очень",
  too: "слишком",
  always: "всегда",
  never: "никогда",
  sometimes: "иногда",
  often: "часто",
  seldom: "редко",
  usually: "обычно",
  already: "уже",
  yet: "ещё",
  soon: "скоро",
  late: "поздно",
  this: "этот",
  that: "тот",
  these: "эти",
  those: "те",
  some: "некоторые",
  any: "любой",
  no: "нет",
  all: "все",
  few: "несколько",
  many: "много",
  most: "большинство",
  much: "много",
  such: "такой",
  each: "каждый",
  every: "каждый",
  both: "оба",
  either: "любой",
};

const serbian = {
  a: "један|jedan",
  an: "један|jedan",
  the: "тај|taj",
  he: "он|on",
  she: "она|ona",
  it: "то|to",
  her: "њена|njena",
  his: "његов|njegov",
  we: "ми|mi",
  they: "они|oni",
  me: "мене|mene",
  us: "нас|nas",
  them: "њих|njih",
  you: "ти|ti",
  I: "ја|ja",
  myself: "себе|sebe",
  yourself: "себе|sebe",
  himself: "себе|sebe",
  herself: "себе|sebe",
  itself: "себе|sebe",
  ourselves: "себе|sebe",
  yourselves: "себе|sebe",
  themselves: "себе|sebe",
  who: "ко|ko",
  whom: "кога|koga",
  whose: "чији|čiji",
  which: "који|koji",
  what: "шта|šta",
  someone: "неко|neko",
  anyone: "било ко|bilo ko",
  everyone: "сви|svi",
  and: "и|i",
  but: "али|ali",
  or: "или|ili",
  nor: "нити|niti",
  yet: "још|još",
  so: "тако|tako",
  however: "међутим|međutim",
  because: "зато што|zato što",
  although: "иако|iako",
  though: "иако|iako",
  since: "од када|od kada",
  if: "ако|ako",
  unless: "осим ако|osim ako",
  while: "док|dok",
  whereas: "док|dok",
  in: "у|u",
  on: "на|na",
  at: "на|na",
  by: "по|po",
  for: "за|za",
  with: "са|sa",
  to: "до|do",
  of: "од|od",
  as: "као|kao",
  between: "између|između",
  through: "кроз|kroz",
  about: "о|o",
  into: "у|u",
  onto: "на|na",
  upon: "на|na",
  beside: "поред|pored",
  behind: "иза|iza",
  within: "унутар|unutar",
  is: "је|je",
  are: "су|su",
  was: "био|bio",
  were: "били|bili",
  am: "сам|sam",
  be: "бити|biti",
  being: "бити|biti",
  been: "био|bio",
  has: "има|ima",
  have: "имају|imaju",
  had: "имао|imao",
  do: "радити|raditi",
  does: "ради|radi",
  did: "радио|radio",
  will: "ће|će",
  would: "би|bi",
  shall: "ће|će",
  should: "треба|treba",
  can: "може|može",
  could: "могао|mogao",
  may: "може|može",
  might: "могао би|mogao bi",
  must: "мора|mora",
  here: "овде|ovde",
  there: "тамо|tamo",
  then: "онда|onda",
  now: "сада|sada",
  very: "веома|veoma",
  too: "превише|previše",
  always: "увек|uvek",
  never: "никада|nikada",
  sometimes: "понекад|ponekad",
  often: "често|često",
  seldom: "ретко|retko",
  usually: "обично|obično",
  already: "већ|već",
  yet: "још|još",
  soon: "ускоро|uskoro",
  late: "касно|kasno",
  this: "ово|ovo",
  that: "то|to",
  these: "ови|ovi",
  those: "они|oni",
  some: "неко|neko",
  any: "било који|bilo koji",
  no: "не|ne",
  all: "сви|svi",
  few: "неколико|nekoliko",
  many: "много|mnogo",
  most: "већина|većina",
  much: "много|mnogo",
  such: "такав|takav",
  each: "сваки|svaki",
  every: "сваки|svaki",
  both: "оба|oba",
  either: "или|ili",
};

const sinhala = {
  a: "එක",
  an: "එක",
  the: "මෙම",
  he: "ඔහු",
  she: "ඇය",
  it: "එය",
  her: "ඇයගේ",
  his: "ඔහුගේ",
  we: "අපි",
  they: "ඔවුන්",
  me: "මට",
  us: "අපට",
  them: "ඔවුන්ට",
  you: "ඔබ",
  I: "මම",
  myself: "මමම",
  yourself: "ඔබම",
  himself: "ඔහුම",
  herself: "ඇයම",
  itself: "එයම",
  ourselves: "අපිම",
  yourselves: "ඔබලාම",
  themselves: "ඔවුන්ම",
  who: "කවුද",
  whom: "කවුරුන්",
  whose: "කවුරුන්ගේ",
  which: "කවර",
  what: "මොකක්ද",
  someone: "කවුරුහරි",
  anyone: "කවුරුහරි",
  everyone: "සියලුම",
  and: "හා",
  but: "නමුත්",
  or: "හෝ",
  nor: "නොහොත්",
  yet: "තවම",
  so: "එසේම",
  however: "කෙසේවෙතත්",
  because: "ඒ නිසා",
  although: "එහෙත්",
  though: "එහෙත්",
  since: "සිට",
  if: "එසේ නම්",
  unless: "නොහොත්",
  while: "තෙක්",
  whereas: "එසේම",
  in: "අතුළ",
  on: "මත",
  at: "විට",
  by: "විසින්",
  for: "සඳහා",
  with: "සමඟ",
  to: "වෙත",
  of: "ගේ",
  as: "වශයෙන්",
  between: "අතර",
  through: "හරහා",
  about: "ගැන",
  into: "අතුළ",
  onto: "මත",
  upon: "මත",
  beside: "පසෙක",
  behind: "පසුපස",
  within: "අතුළ",
  is: "වේ",
  are: "වේ",
  was: "විය",
  were: "විය",
  am: "මම",
  be: "වීම",
  being: "වීම",
  been: "වී ඇත",
  has: "ඇත",
  have: "ඇත",
  had: "විය",
  do: "කරන්න",
  does: "කරයි",
  did: "කළා",
  will: "වෙනු ඇත",
  would: "වෙනු ඇත",
  shall: "වෙනු ඇත",
  should: "විය යුතුය",
  can: "හැක",
  could: "හැකි විය",
  may: "හැක",
  might: "හැකි විය",
  must: "අවශ්‍යයි",
  here: "මෙහි",
  there: "එහි",
  then: "එවිට",
  now: "දැන්",
  very: "ඉතා",
  too: "ද",
  always: "සෑම විටම",
  never: "කවදාවත්",
  sometimes: "කලින්",
  often: "බොහෝ විට",
  seldom: "අඩුම",
  usually: "සාමාන්‍යයෙන්",
  already: "දැනටමත්",
  yet: "තවම",
  soon: "ඉක්මනින්",
  late: "නැසී",
  this: "මෙම",
  that: "ඒ",
  these: "මෙම",
  those: "ඒ",
  some: "සමහර",
  any: "කිසිවක්",
  no: "නැත",
  all: "සියලුම",
  few: "අඩුම",
  many: "බොහෝ",
  most: "බොහෝම",
  much: "බොහෝ",
  such: "එවැනි",
  each: "සෑම",
  every: "සෑම",
  both: "දෙකම",
  either: "කිසිවක්",
};

const somali = {
  a: "hal",
  an: "hal",
  the: "kan",
  he: "isaga",
  she: "iyada",
  it: "waxaa",
  her: "iyada",
  his: "isaga",
  we: "annaga",
  they: "iyaga",
  me: "aniga",
  us: "annaga",
  them: "iyaga",
  you: "adiga",
  I: "aniga",
  myself: "aniga qudhayda",
  yourself: "adiga qudhaada",
  himself: "isaga qudhiisa",
  herself: "iyada qudheeda",
  itself: "waxaa qudhiisa",
  ourselves: "annaga qudhayada",
  yourselves: "adinka qudhayada",
  themselves: "iyaga qudhayada",
  who: "yaa",
  whom: "yaa",
  whose: "yaa leh",
  which: "kee",
  what: "maxay",
  someone: "qof",
  anyone: "qof kasta",
  everyone: "qof walba",
  and: "iyo",
  but: "laakiin",
  or: "ama",
  nor: "mana",
  yet: "wali",
  so: "sidaa darteed",
  however: "si kastaba ha ahaatee",
  because: "sababtoo ah",
  although: "inkastoo",
  though: "inkastoo",
  since: "tan iyo",
  if: "haddii",
  unless: "haddii aan",
  while: "inta lagu jiro",
  whereas: "halka",
  in: "gudaha",
  on: "dusha",
  at: "meesha",
  by: "by",
  for: "u",
  with: "la",
  to: "si",
  of: "ka",
  as: "sida",
  between: "dhexeeya",
  through: "iyadoo loo marayo",
  about: "ku saabsan",
  into: "gudaha",
  onto: "dusha",
  upon: "dusha",
  beside: "agtiisa",
  behind: "dhabarka",
  within: "gudaha",
  is: "waa",
  are: "waa",
  was: "wuxuu ahaa",
  were: "waxay ahaayeen",
  am: "aniga",
  be: "noqon",
  being: "noqonaya",
  been: "noqday",
  has: "waxaa leh",
  have: "waxaa leh",
  had: "waxaa lahaa",
  do: "samee",
  does: "sameeyaa",
  did: "sameeyay",
  will: "doono",
  would: "doono",
  shall: "doono",
  should: "waa in",
  can: "karin",
  could: "karin",
  may: "karin",
  might: "karin",
  must: "waa in",
  here: "halkan",
  there: "halkaas",
  then: "ka dib",
  now: "hadda",
  very: "aad",
  too: "aad",
  always: "mar walba",
  never: "waligaa",
  sometimes: "mararka qaar",
  often: "inta badan",
  seldom: "dhif",
  usually: "caadi ahaan",
  already: "horey",
  yet: "wali",
  soon: "dhawaan",
  late: "goor dambe",
  this: "kan",
  that: "kaas",
  these: "kuwaan",
  those: "kuwaas",
  some: "qaar",
  any: "wax kasta",
  no: "maya",
  all: "dhammaan",
  few: "yar",
  many: "badan",
  most: "inta badan",
  much: "badan",
  such: "sidaas",
  each: "mid kasta",
  every: "kasta",
  both: "labadaba",
  either: "midkood",
};

const swahili = {
  a: "moja",
  an: "moja",
  the: "hii",
  he: "yeye",
  she: "yeye",
  it: "hii",
  her: "yake",
  his: "yake",
  we: "sisi",
  they: "wao",
  me: "mimi",
  us: "sisi",
  them: "wao",
  you: "wewe",
  I: "mimi",
  myself: "mimi mwenyewe",
  yourself: "wewe mwenyewe",
  himself: "yeye mwenyewe",
  herself: "yeye mwenyewe",
  itself: "hii yenyewe",
  ourselves: "sisi wenyewe",
  yourselves: "ninyi wenyewe",
  themselves: "wao wenyewe",
  who: "nani",
  whom: "nani",
  whose: "nani",
  which: "ambayo",
  what: "nini",
  someone: "mtu",
  anyone: "mtu yeyote",
  everyone: "kila mtu",
  and: "na",
  but: "lakini",
  or: "au",
  nor: "wala",
  yet: "bado",
  so: "kwa hivyo",
  however: "hata hivyo",
  because: "kwa sababu",
  although: "ingawa",
  though: "ingawa",
  since: "tangu",
  if: "ikiwa",
  unless: "isipokuwa",
  while: "wakati",
  whereas: "ilhali",
  in: "ndani",
  on: "juu",
  at: "kwa",
  by: "na",
  for: "kwa",
  with: "na",
  to: "kwa",
  of: "ya",
  as: "kama",
  between: "kati",
  through: "kupitia",
  about: "kuhusu",
  into: "ndani",
  onto: "juu",
  upon: "juu",
  beside: "karibu",
  behind: "nyuma",
  within: "ndani",
  is: "ni",
  are: "ni",
  was: "alikuwa",
  were: "walikuwa",
  am: "niko",
  be: "kuwa",
  being: "kuwa",
  been: "imekuwa",
  has: "ana",
  have: "wana",
  had: "alikuwa na",
  do: "fanya",
  does: "anafanya",
  did: "alifanya",
  will: "atafanya",
  would: "angefanya",
  shall: "atakua",
  should: "inapaswa",
  can: "inaweza",
  could: "ingeweza",
  may: "inaweza",
  might: "inaweza",
  must: "lazima",
  here: "hapa",
  there: "hapo",
  then: "kisha",
  now: "sasa",
  very: "sana",
  too: "pia",
  always: "daima",
  never: "kamwe",
  sometimes: "wakati mwingine",
  often: "mara nyingi",
  seldom: "nadra",
  usually: "kawaida",
  already: "tayari",
  yet: "bado",
  soon: "karibuni",
  late: "marehemu",
  this: "hii",
  that: "hiyo",
  these: "hizi",
  those: "hizo",
  some: "baadhi",
  any: "yoyote",
  no: "hapana",
  all: "wote",
  few: "wachache",
  many: "wengi",
  most: "zaidi",
  much: "mengi",
  such: "kama",
  each: "kila",
  every: "kila",
  both: "wote",
  either: "ama",
};

const tamil = {
  a: "ஒரு",
  an: "ஒரு",
  the: "அந்த",
  he: "அவர்",
  she: "அவள்",
  it: "அது",
  her: "அவளது",
  his: "அவரது",
  we: "நாம்",
  they: "அவர்கள்",
  me: "என்னை",
  us: "எங்களை",
  them: "அவர்களை",
  you: "நீ",
  I: "நான்",
  myself: "நான்",
  yourself: "நீயே",
  himself: "அவரே",
  herself: "அவளே",
  itself: "அதே",
  ourselves: "நாங்கள்",
  yourselves: "நீங்கள்",
  themselves: "அவர்களே",
  who: "யார்",
  whom: "யாருக்கு",
  whose: "யாருடைய",
  which: "எது",
  what: "என்ன",
  someone: "யாரோ",
  anyone: "யாராவது",
  everyone: "எல்லாரும்",
  and: "மற்றும்",
  but: "ஆனால்",
  or: "அல்லது",
  nor: "அல்லது",
  yet: "இன்னும்",
  so: "ஆகவே",
  however: "எப்படியாவது",
  because: "ஏனெனில்",
  although: "என்றாலும்",
  though: "என்றாலும்",
  since: "முதல்",
  if: "என்றால்",
  unless: "அல்லாமல்",
  while: "போது",
  whereas: "என்றால்",
  in: "உள்ள",
  on: "மேல்",
  at: "இல்",
  by: "மூலம்",
  for: "காக",
  with: "உடன்",
  to: "க்கு",
  of: "இன்",
  as: "போல்",
  between: "இடையில்",
  through: "மூலம்",
  about: "பற்றி",
  into: "உள்ளே",
  onto: "மேல்",
  upon: "மேல்",
  beside: "அருகில்",
  behind: "பின்னால்",
  within: "உள்ளே",
  is: "இருக்கிறது",
  are: "இருக்கின்றன",
  was: "இருந்தது",
  were: "இருந்தன",
  am: "நான்",
  be: "இரு",
  being: "இருக்கிறது",
  been: "இருந்தது",
  has: "உள்ளது",
  have: "உள்ளன",
  had: "இருந்தது",
  do: "செய்",
  does: "செய்கிறது",
  did: "செய்தது",
  will: "விரும்புகிறது",
  would: "விரும்பும்",
  shall: "வேண்டும்",
  should: "வேண்டும்",
  can: "முடியும்",
  could: "முடியும்",
  may: "முடியும்",
  might: "முடியும்",
  must: "வேண்டும்",
  here: "இங்கே",
  there: "அங்கே",
  then: "அப்பொழுது",
  now: "இப்போது",
  very: "மிகவும்",
  too: "மிகவும்",
  always: "எப்பொழுதும்",
  never: "ஒருபோதும்",
  sometimes: "சில சமயம்",
  often: "அடிக்கடி",
  seldom: "அரிதாக",
  usually: "வழக்கமாக",
  already: "ஏற்கனவே",
  yet: "இன்னும்",
  soon: "விரைவில்",
  late: "தாமதமாக",
  this: "இந்த",
  that: "அந்த",
  these: "இந்த",
  those: "அந்த",
  some: "சில",
  any: "ஏதேனும்",
  no: "இல்லை",
  all: "அனைத்து",
  few: "சில",
  many: "பல",
  most: "மிகவும்",
  much: "மிகவும்",
  such: "அந்த",
  each: "ஒவ்வொரு",
  every: "ஒவ்வொரு",
  both: "இரண்டும்",
  either: "ஒன்றும்",
};

const telugu = {
  a: "ఒక",
  an: "ఒక",
  the: "ఆ",
  he: "అతను",
  she: "ఆమె",
  it: "అది",
  her: "ఆమె",
  his: "అతని",
  we: "మేము",
  they: "వారు",
  me: "నన్ను",
  us: "మమ్మల్ని",
  them: "వారిని",
  you: "నువ్వు",
  I: "నేను",
  myself: "నేనే",
  yourself: "నువ్వే",
  himself: "తానే",
  herself: "ఆమెనే",
  itself: "దాన్నే",
  ourselves: "మేమే",
  yourselves: "మీరు",
  themselves: "వారే",
  who: "ఎవరు",
  whom: "ఎవరిని",
  whose: "ఎవరి",
  which: "ఏది",
  what: "ఏమి",
  someone: "ఎవరైనా",
  anyone: "ఎవరైనా",
  everyone: "ప్రతివారు",
  and: "మరియు",
  but: "కానీ",
  or: "లేదా",
  nor: "కూడా కాదు",
  yet: "ఇప్పటికీ",
  so: "కాబట్టి",
  however: "అయితే",
  because: "ఎందుకంటే",
  although: "అయినా",
  though: "అయినా",
  since: "నుండి",
  if: "ఒకవేళ",
  unless: "లేకపోతే",
  while: "అయితే",
  whereas: "అయితే",
  in: "లో",
  on: "పై",
  at: "వద్ద",
  by: "ద్వారా",
  for: "కోసం",
  with: "తో",
  to: "కు",
  of: "యొక్క",
  as: "వంటి",
  between: "మధ్య",
  through: "ద్వారా",
  about: "గురించి",
  into: "లోపల",
  onto: "పైకి",
  upon: "పై",
  beside: "పక్కన",
  behind: "వెనుక",
  within: "లోపల",
  is: "ఉంది",
  are: "ఉన్నాయి",
  was: "ఉంది",
  were: "ఉన్నాయి",
  am: "నేను",
  be: "ఉండాలి",
  being: "ఉండటం",
  been: "ఉంది",
  has: "ఉంది",
  have: "ఉన్నాయి",
  had: "ఉంది",
  do: "చేయండి",
  does: "చేస్తుంది",
  did: "చేసింది",
  will: "చేస్తుంది",
  would: "చేస్తుంది",
  shall: "చేస్తుంది",
  should: "చేయాలి",
  can: "చేయగలరు",
  could: "చేయగలరు",
  may: "చేయవచ్చు",
  might: "చేయవచ్చు",
  must: "చేయాలి",
  here: "ఇక్కడ",
  there: "అక్కడ",
  then: "అప్పుడు",
  now: "ఇప్పుడు",
  very: "చాలా",
  too: "కూడా",
  always: "ఎప్పుడూ",
  never: "ఎప్పుడూ కాదు",
  sometimes: "కొన్నిసార్లు",
  often: "తరచుగా",
  seldom: "అరుదుగా",
  usually: "సాధారణంగా",
  already: "ఇప్పటికే",
  yet: "ఇప్పటికీ",
  soon: "త్వరలో",
  late: "ఆలస్యంగా",
  this: "ఈ",
  that: "ఆ",
  these: "ఈ",
  those: "ఆ",
  some: "కొన్ని",
  any: "ఏదైనా",
  no: "లేదు",
  all: "అన్ని",
  few: "కొన్ని",
  many: "చాలా",
  most: "చాలా",
  much: "చాలా",
  such: "అటువంటి",
  each: "ప్రతి",
  every: "ప్రతి",
  both: "రెండు",
  either: "ఏదో ఒకటి",
};

const thai = {
  a: "หนึ่ง",
  an: "หนึ่ง",
  the: "ที่",
  he: "เขา",
  she: "เธอ",
  it: "มัน",
  her: "ของเธอ",
  his: "ของเขา",
  we: "เรา",
  they: "พวกเขา",
  me: "ฉัน",
  us: "พวกเรา",
  them: "พวกเขา",
  you: "คุณ",
  I: "ฉัน",
  myself: "ตัวฉันเอง",
  yourself: "ตัวคุณเอง",
  himself: "ตัวเขาเอง",
  herself: "ตัวเธอเอง",
  itself: "ตัวมันเอง",
  ourselves: "ตัวเราเอง",
  yourselves: "ตัวคุณเอง",
  themselves: "ตัวพวกเขาเอง",
  who: "ใคร",
  whom: "ใคร",
  whose: "ของใคร",
  which: "อันไหน",
  what: "อะไร",
  someone: "บางคน",
  anyone: "ใครก็ได้",
  everyone: "ทุกคน",
  and: "และ",
  but: "แต่",
  or: "หรือ",
  nor: "ไม่",
  yet: "ยัง",
  so: "ดังนั้น",
  however: "อย่างไรก็ตาม",
  because: "เพราะว่า",
  although: "แม้ว่า",
  though: "แม้ว่า",
  since: "ตั้งแต่",
  if: "ถ้า",
  unless: "เว้นแต่",
  while: "ในขณะที่",
  whereas: "ในขณะที่",
  in: "ใน",
  on: "บน",
  at: "ที่",
  by: "โดย",
  for: "สำหรับ",
  with: "กับ",
  to: "ไปยัง",
  of: "ของ",
  as: "เป็น",
  between: "ระหว่าง",
  through: "ผ่าน",
  about: "เกี่ยวกับ",
  into: "เข้าไปใน",
  onto: "บน",
  upon: "บน",
  beside: "ข้าง",
  behind: "หลัง",
  within: "ภายใน",
  is: "เป็น",
  are: "เป็น",
  was: "เป็น",
  were: "เป็น",
  am: "เป็น",
  be: "เป็น",
  being: "เป็น",
  been: "เป็น",
  has: "มี",
  have: "มี",
  had: "มี",
  do: "ทำ",
  does: "ทำ",
  did: "ทำ",
  will: "จะ",
  would: "จะ",
  shall: "จะ",
  should: "ควร",
  can: "สามารถ",
  could: "สามารถ",
  may: "อาจ",
  might: "อาจ",
  must: "ต้อง",
  here: "ที่นี่",
  there: "ที่นั่น",
  then: "แล้ว",
  now: "ตอนนี้",
  very: "มาก",
  too: "เกินไป",
  always: "เสมอ",
  never: "ไม่เคย",
  sometimes: "บางครั้ง",
  often: "บ่อย",
  seldom: "ไม่บ่อย",
  usually: "ปกติ",
  already: "แล้ว",
  yet: "ยัง",
  soon: "เร็วๆนี้",
  late: "สาย",
  this: "นี้",
  that: "นั้น",
  these: "เหล่านี้",
  those: "เหล่านั้น",
  some: "บาง",
  any: "ใดๆ",
  no: "ไม่",
  all: "ทั้งหมด",
  few: "น้อย",
  many: "หลาย",
  most: "ส่วนใหญ่",
  much: "มาก",
  such: "เช่น",
  each: "แต่ละ",
  every: "ทุก",
  both: "ทั้งสอง",
  either: "อย่างใดอย่างหนึ่ง",
};

const tigrinya = {
  a: "አንድ",
  an: "አንድ",
  the: "ዝኾነ",
  he: "ንሱ",
  she: "ንሳ",
  it: "እቲ",
  her: "ናታ",
  his: "ናቱ",
  we: "ንሕና",
  they: "ንሳቶም",
  me: "ኣነ",
  us: "ንሕና",
  them: "ንሳቶም",
  you: "ንስኻ",
  I: "ኣነ",
  myself: "ኣነ ሓደ",
  yourself: "ንስኻ ሓደ",
  himself: "ንሱ ሓደ",
  herself: "ንሳ ሓደ",
  itself: "እቲ ሓደ",
  ourselves: "ንሕና ሓደ",
  yourselves: "ንስኻትኩም ሓደ",
  themselves: "ንሳቶም ሓደ",
  who: "መን",
  whom: "መን",
  whose: "ናባ",
  which: "እዚ",
  what: "እንታይ",
  someone: "ኣንደሓደ",
  anyone: "ኣንደሓደ",
  everyone: "ኩሉ",
  and: "ንምስ",
  but: "ግን",
  or: "ወይ",
  nor: "ኣይኮነን",
  yet: "እዚኣን",
  so: "ስለዚ",
  however: "እንተዘይኮነ",
  because: "ምኽንያቱ",
  although: "እንተዘይኮነ",
  though: "እንተዘይኮነ",
  since: "ካብ",
  if: "እንተ",
  unless: "እንተዘይኮነ",
  while: "እዋን",
  whereas: "እዋን",
  in: "ኣብ",
  on: "ኣብ",
  at: "ኣብ",
  by: "ብ",
  for: "ን",
  with: "ንምስ",
  to: "ን",
  of: "ናብ",
  as: "ከም",
  between: "ኣብ መንጎ",
  through: "ብ",
  about: "ብዛዕባ",
  into: "ኣብ",
  onto: "ኣብ",
  upon: "ኣብ",
  beside: "ኣብ ጎኒ",
  behind: "ኣብ ድሕሪ",
  within: "ኣብ ውሽጢ",
  is: "እዩ",
  are: "እዮም",
  was: "ነበረ",
  were: "ነበረ",
  am: "እየ",
  be: "ክኸውን",
  being: "እዩ",
  been: "ነበረ",
  has: "ኣሎ",
  have: "ኣሎ",
  had: "ነበረ",
  do: "ምግባር",
  does: "ምግባር",
  did: "ገበረ",
  will: "ክኸውን",
  would: "ክኸውን",
  shall: "ክኸውን",
  should: "ክኸውን",
  can: "ክኸውን",
  could: "ክኸውን",
  may: "ክኸውን",
  might: "ክኸውን",
  must: "ክኸውን",
  here: "ኣብዚ",
  there: "ኣብኣቲ",
  then: "ኣብዚኣን",
  now: "ሕጂ",
  very: "ብጣዕሚ",
  too: "እንከሎ",
  always: "ኩሉ ግዜ",
  never: "ኣይኮነን",
  sometimes: "እዋን እዋን",
  often: "ብዙሕ ግዜ",
  seldom: "እዋን እዋን",
  usually: "እዋን እዋን",
  already: "ኣብ ዝሓለፈ",
  yet: "እዚኣን",
  soon: "ብቕልጡፍ",
  late: "ኣብ ድሕሪ",
  this: "እዚ",
  that: "እቲ",
  these: "እዚኦም",
  those: "እቶም",
  some: "ኣንዳንዶ",
  any: "ኣንዳንዶ",
  no: "ኣይኮነን",
  all: "ኩሉ",
  few: "ኣንዳንዶ",
  many: "ብዙሕ",
  most: "ብዙሕ",
  much: "ብዙሕ",
  such: "ከምኡ",
  each: "ኣንዳንዶ",
  every: "ኩሉ",
  both: "ክልቲኡ",
  either: "ኣንዲ",
};

const turkce = {
  a: "bir",
  an: "bir",
  the: "bu",
  he: "o",
  she: "o",
  it: "o",
  her: "onun",
  his: "onun",
  we: "biz",
  they: "onlar",
  me: "beni",
  us: "bizi",
  them: "onları",
  you: "sen",
  I: "ben",
  myself: "kendim",
  yourself: "kendin",
  himself: "kendisi",
  herself: "kendisi",
  itself: "kendisi",
  ourselves: "kendimiz",
  yourselves: "kendiniz",
  themselves: "kendileri",
  who: "kim",
  whom: "kimi",
  whose: "kimin",
  which: "hangi",
  what: "ne",
  someone: "biri",
  anyone: "herhangi biri",
  everyone: "herkes",
  and: "ve",
  but: "ama",
  or: "veya",
  nor: "ne de",
  yet: "henüz",
  so: "bu yüzden",
  however: "ancak",
  because: "çünkü",
  although: "olmasına rağmen",
  though: "olmasına rağmen",
  since: "çünkü",
  if: "eğer",
  unless: "olmadıkça",
  while: "iken",
  whereas: "oysa",
  in: "içinde",
  on: "üzerinde",
  at: "de",
  by: "tarafından",
  for: "için",
  with: "ile",
  to: "kadar",
  of: "nin",
  as: "olarak",
  between: "arasında",
  through: "aracılığıyla",
  about: "hakkında",
  into: "içine",
  onto: "üzerine",
  upon: "üzerine",
  beside: "yanında",
  behind: "arkasında",
  within: "içinde",
  is: "dir",
  are: "dir",
  was: "idi",
  were: "idi",
  am: "im",
  be: "olmak",
  being: "olmak",
  been: "oldu",
  has: "var",
  have: "var",
  had: "vardı",
  do: "yapmak",
  does: "yapar",
  did: "yaptı",
  will: "olacak",
  would: "olurdu",
  shall: "olacak",
  should: "olmalı",
  can: "yapabilir",
  could: "yapabilirdi",
  may: "olabilir",
  might: "olabilir",
  must: "zorunda",
  here: "burada",
  there: "orada",
  then: "sonra",
  now: "şimdi",
  very: "çok",
  too: "çok",
  always: "her zaman",
  never: "asla",
  sometimes: "bazen",
  often: "sık sık",
  seldom: "nadiren",
  usually: "genellikle",
  already: "zaten",
  yet: "henüz",
  soon: "yakında",
  late: "geç",
  this: "bu",
  that: "şu",
  these: "bunlar",
  those: "şunlar",
  some: "bazı",
  any: "herhangi",
  no: "hayır",
  all: "tüm",
  few: "birkaç",
  many: "birçok",
  most: "çoğu",
  much: "çok",
  such: "böyle",
  each: "her biri",
  every: "her",
  both: "her ikisi",
  either: "her ikisi de",
};

const ukchina = {
  a: "一个|一個",
  an: "一个|一個",
  the: "这|這",
  he: "他|他",
  she: "她|她",
  it: "它|它",
  her: "她的|她的",
  his: "他的|他的",
  we: "我们|我們",
  they: "他们|他們",
  me: "我|我",
  us: "我们|我們",
  them: "他们|他們",
  you: "你|你",
  I: "我|我",
  myself: "我自己|我自己",
  yourself: "你自己|你自己",
  himself: "他自己|他自己",
  herself: "她自己|她自己",
  itself: "它自己|它自己",
  ourselves: "我们自己|我們自己",
  yourselves: "你们自己|你們自己",
  themselves: "他们自己|他們自己",
  who: "谁|誰",
  whom: "谁|誰",
  whose: "谁的|誰的",
  which: "哪个|哪個",
  what: "什么|什麼",
  someone: "某人|某人",
  anyone: "任何人|任何人",
  everyone: "每个人|每個人",
  and: "和|和",
  but: "但是|但是",
  or: "或者|或者",
  nor: "也不|也不",
  yet: "然而|然而",
  so: "所以|所以",
  however: "然而|然而",
  because: "因为|因為",
  although: "虽然|雖然",
  though: "虽然|雖然",
  since: "自从|自從",
  if: "如果|如果",
  unless: "除非|除非",
  while: "当|當",
  whereas: "而|而",
  in: "在|在",
  on: "在|在",
  at: "在|在",
  by: "通过|通過",
  for: "为了|為了",
  with: "与|與",
  to: "到|到",
  of: "的|的",
  as: "作为|作為",
  between: "在|之间|在|之間",
  through: "通过|通過",
  about: "关于|關於",
  into: "进入|進入",
  onto: "到|上|到|上",
  upon: "在|上|在|上",
  beside: "在|旁边|在|旁邊",
  behind: "在|后面|在|後面",
  within: "在|内|在|內",
  is: "是|是",
  are: "是|是",
  was: "是|是",
  were: "是|是",
  am: "是|是",
  be: "是|是",
  being: "是|是",
  been: "是|是",
  has: "有|有",
  have: "有|有",
  had: "有|有",
  do: "做|做",
  does: "做|做",
  did: "做|做",
  will: "将|將",
  would: "将|將",
  shall: "将|將",
  should: "应该|應該",
  can: "能|能",
  could: "能|能",
  may: "可以|可以",
  might: "可能|可能",
  must: "必须|必須",
  here: "这里|這裡",
  there: "那里|那裡",
  then: "然后|然後",
  now: "现在|現在",
  very: "非常|非常",
  too: "太|太",
  always: "总是|總是",
  never: "从不|從不",
  sometimes: "有时|有時",
  often: "经常|經常",
  seldom: "很少|很少",
  usually: "通常|通常",
  already: "已经|已經",
  yet: "还|還",
  soon: "很快|很快",
  late: "晚|晚",
  this: "这个|這個",
  that: "那个|那個",
  these: "这些|這些",
  those: "那些|那些",
  some: "一些|一些",
  any: "任何|任何",
  no: "没有|沒有",
  all: "所有|所有",
  few: "少数|少數",
  many: "许多|許多",
  most: "大多数|大多數",
  much: "很多|很多",
  such: "这样的|這樣的",
  each: "每个|每個",
  every: "每个|每個",
  both: "两个|兩個",
  either: "任一|任一",
};

const ukrainian = {
  a: "один",
  an: "один",
  the: "цей",
  he: "він",
  she: "вона",
  it: "воно",
  her: "її",
  his: "його",
  we: "ми",
  they: "вони",
  me: "мене",
  us: "нас",
  them: "їх",
  you: "ти",
  I: "я",
  myself: "себе",
  yourself: "себе",
  himself: "себе",
  herself: "себе",
  itself: "себе",
  ourselves: "себе",
  yourselves: "себе",
  themselves: "себе",
  who: "хто",
  whom: "кого",
  whose: "чий",
  which: "який",
  what: "що",
  someone: "хтось",
  anyone: "будь-хто",
  everyone: "всі",
  and: "і",
  but: "але",
  or: "або",
  nor: "ні",
  yet: "ще",
  so: "так",
  however: "однак",
  because: "тому що",
  although: "хоча",
  though: "хоча",
  since: "з",
  if: "якщо",
  unless: "якщо не",
  while: "поки",
  whereas: "тоді як",
  in: "в",
  on: "на",
  at: "в",
  by: "за",
  for: "для",
  with: "з",
  to: "до",
  of: "з",
  as: "як",
  between: "між",
  through: "через",
  about: "про",
  into: "в",
  onto: "на",
  upon: "на",
  beside: "поруч",
  behind: "позаду",
  within: "всередині",
  is: "є",
  are: "є",
  was: "був",
  were: "були",
  am: "є",
  be: "бути",
  being: "бути",
  been: "був",
  has: "має",
  have: "мають",
  had: "мав",
  do: "робити",
  does: "робить",
  did: "робив",
  will: "буде",
  would: "був би",
  shall: "буде",
  should: "повинен",
  can: "може",
  could: "міг",
  may: "може",
  might: "може",
  must: "повинен",
  here: "тут",
  there: "там",
  then: "тоді",
  now: "зараз",
  very: "дуже",
  too: "занадто",
  always: "завжди",
  never: "ніколи",
  sometimes: "іноді",
  often: "часто",
  seldom: "рідко",
  usually: "зазвичай",
  already: "вже",
  yet: "ще",
  soon: "скоро",
  late: "пізно",
  this: "цей",
  that: "той",
  these: "ці",
  those: "ті",
  some: "деякі",
  any: "будь-який",
  no: "ні",
  all: "всі",
  few: "кілька",
  many: "багато",
  most: "більшість",
  much: "багато",
  such: "такий",
  each: "кожен",
  every: "кожен",
  both: "обидва",
  either: "будь-який",
};

const urdu = {
  a: "ایک",
  an: "ایک",
  the: "یہ",
  he: "وہ",
  she: "وہ",
  it: "یہ",
  her: "اس کی",
  his: "اس کا",
  we: "ہم",
  they: "وہ",
  me: "مجھے",
  us: "ہمیں",
  them: "انہیں",
  you: "آپ",
  I: "میں",
  myself: "خود",
  yourself: "خود",
  himself: "خود",
  herself: "خود",
  itself: "خود",
  ourselves: "خود",
  yourselves: "خود",
  themselves: "خود",
  who: "کون",
  whom: "کسے",
  whose: "کس کا",
  which: "کون سا",
  what: "کیا",
  someone: "کوئی",
  anyone: "کوئی بھی",
  everyone: "ہر کوئی",
  and: "اور",
  but: "لیکن",
  or: "یا",
  nor: "نہ",
  yet: "ابھی تک",
  so: "تو",
  however: "تاہم",
  because: "کیونکہ",
  although: "اگرچہ",
  though: "اگرچہ",
  since: "چونکہ",
  if: "اگر",
  unless: "جب تک",
  while: "جبکہ",
  whereas: "جہاں",
  in: "میں",
  on: "پر",
  at: "پر",
  by: "کی طرف سے",
  for: "کے لئے",
  with: "کے ساتھ",
  to: "کو",
  of: "کا",
  as: "کے طور پر",
  between: "کے درمیان",
  through: "کے ذریعے",
  about: "کے بارے میں",
  into: "میں",
  onto: "پر",
  upon: "پر",
  beside: "کے ساتھ",
  behind: "کے پیچھے",
  within: "کے اندر",
  is: "ہے",
  are: "ہیں",
  was: "تھا",
  were: "تھے",
  am: "ہوں",
  be: "ہونا",
  being: "ہو رہا ہے",
  been: "ہو چکا ہے",
  has: "ہے",
  have: "ہیں",
  had: "تھا",
  do: "کرتے ہیں",
  does: "کرتا ہے",
  did: "کیا",
  will: "کرے گا",
  would: "کرے گا",
  shall: "کرے گا",
  should: "چاہیے",
  can: "کر سکتا ہے",
  could: "کر سکتا تھا",
  may: "ہو سکتا ہے",
  might: "ہو سکتا ہے",
  must: "ضرور",
  here: "یہاں",
  there: "وہاں",
  then: "پھر",
  now: "اب",
  very: "بہت",
  too: "بھی",
  always: "ہمیشہ",
  never: "کبھی نہیں",
  sometimes: "کبھی کبھی",
  often: "اکثر",
  seldom: "شاذ و نادر",
  usually: "عام طور پر",
  already: "پہلے ہی",
  yet: "ابھی تک",
  soon: "جلد",
  late: "دیر",
  this: "یہ",
  that: "وہ",
  these: "یہ",
  those: "وہ",
  some: "کچھ",
  any: "کوئی بھی",
  no: "نہیں",
  all: "سب",
  few: "کچھ",
  many: "بہت سے",
  most: "زیادہ تر",
  much: "بہت",
  such: "ایسا",
  each: "ہر ایک",
  every: "ہر",
  both: "دونوں",
  either: "یا",
};

const uzbek = {
  a: "bir",
  an: "bir",
  the: "bu",
  he: "u",
  she: "u",
  it: "bu",
  her: "uning",
  his: "uning",
  we: "biz",
  they: "ular",
  me: "meni",
  us: "bizni",
  them: "ularni",
  you: "siz",
  I: "men",
  myself: "o'zim",
  yourself: "o'zingiz",
  himself: "o'zi",
  herself: "o'zi",
  itself: "o'zi",
  ourselves: "o'zimiz",
  yourselves: "o'zingiz",
  themselves: "o'zlari",
  who: "kim",
  whom: "kimni",
  whose: "kimning",
  which: "qaysi",
  what: "nima",
  someone: "kimdir",
  anyone: "har kim",
  everyone: "hamma",
  and: "va",
  but: "lekin",
  or: "yoki",
  nor: "na",
  yet: "hali",
  so: "shunday",
  however: "ammo",
  because: "chunki",
  although: "garchi",
  though: "garchi",
  since: "dan beri",
  if: "agar",
  unless: "agar bo'lmasa",
  while: "paytda",
  whereas: "holbuki",
  in: "ichida",
  on: "ustida",
  at: "da",
  by: "tomonidan",
  for: "uchun",
  with: "bilan",
  to: "ga",
  of: "ning",
  as: "sifatida",
  between: "o'rtasida",
  through: "orqali",
  about: "haqida",
  into: "ichiga",
  onto: "ustiga",
  upon: "ustiga",
  beside: "yonida",
  behind: "orqasida",
  within: "ichida",
  is: "bo'ladi",
  are: "bo'ladi",
  was: "edi",
  were: "edi",
  am: "man",
  be: "bo'lish",
  being: "bo'lish",
  been: "bo'lgan",
  has: "bor",
  have: "bor",
  had: "bor edi",
  do: "qilmoq",
  does: "qiladi",
  did: "qildi",
  will: "bo'ladi",
  would: "bo'lardi",
  shall: "bo'ladi",
  should: "kerak",
  can: "mumkin",
  could: "mumkin edi",
  may: "mumkin",
  might: "mumkin",
  must: "kerak",
  here: "bu yerda",
  there: "u yerda",
  then: "keyin",
  now: "hozir",
  very: "juda",
  too: "ham",
  always: "doim",
  never: "hech qachon",
  sometimes: "ba'zan",
  often: "ko'pincha",
  seldom: "kamdan-kam",
  usually: "odatda",
  already: "allaqachon",
  yet: "hali",
  soon: "tez orada",
  late: "kech",
  this: "bu",
  that: "u",
  these: "bu",
  those: "u",
  some: "ba'zi",
  any: "har qanday",
  no: "yo'q",
  all: "hamma",
  few: "bir necha",
  many: "ko'p",
  most: "ko'pchilik",
  much: "ko'p",
  such: "bunday",
  each: "har biri",
  every: "har bir",
  both: "ikkalasi",
  either: "yoki",
};

const vietnamese = {
  a: "một",
  an: "một",
  the: "cái",
  he: "anh ấy",
  she: "cô ấy",
  it: "nó",
  her: "của cô ấy",
  his: "của anh ấy",
  we: "chúng tôi",
  they: "họ",
  me: "tôi",
  us: "chúng tôi",
  them: "họ",
  you: "bạn",
  I: "tôi",
  myself: "bản thân tôi",
  yourself: "bản thân bạn",
  himself: "bản thân anh ấy",
  herself: "bản thân cô ấy",
  itself: "bản thân nó",
  ourselves: "bản thân chúng tôi",
  yourselves: "bản thân các bạn",
  themselves: "bản thân họ",
  who: "ai",
  whom: "ai",
  whose: "của ai",
  which: "cái nào",
  what: "gì",
  someone: "ai đó",
  anyone: "bất kỳ ai",
  everyone: "mọi người",
  and: "và",
  but: "nhưng",
  or: "hoặc",
  nor: "cũng không",
  yet: "chưa",
  so: "vì vậy",
  however: "tuy nhiên",
  because: "bởi vì",
  although: "mặc dù",
  though: "mặc dù",
  since: "kể từ khi",
  if: "nếu",
  unless: "trừ khi",
  while: "trong khi",
  whereas: "trong khi",
  in: "trong",
  on: "trên",
  at: "tại",
  by: "bởi",
  for: "cho",
  with: "với",
  to: "đến",
  of: "của",
  as: "như",
  between: "giữa",
  through: "qua",
  about: "về",
  into: "vào",
  onto: "lên",
  upon: "trên",
  beside: "bên cạnh",
  behind: "đằng sau",
  within: "trong",
  is: "là",
  are: "là",
  was: "đã",
  were: "đã",
  am: "là",
  be: "là",
  being: "đang",
  been: "đã",
  has: "có",
  have: "có",
  had: "đã có",
  do: "làm",
  does: "làm",
  did: "đã làm",
  will: "sẽ",
  would: "sẽ",
  shall: "sẽ",
  should: "nên",
  can: "có thể",
  could: "có thể",
  may: "có thể",
  might: "có thể",
  must: "phải",
  here: "đây",
  there: "đó",
  then: "sau đó",
  now: "bây giờ",
  very: "rất",
  too: "quá",
  always: "luôn luôn",
  never: "không bao giờ",
  sometimes: "đôi khi",
  often: "thường",
  seldom: "hiếm khi",
  usually: "thường",
  already: "đã",
  yet: "chưa",
  soon: "sớm",
  late: "muộn",
  this: "này",
  that: "đó",
  these: "những",
  those: "những",
  some: "một số",
  any: "bất kỳ",
  no: "không",
  all: "tất cả",
  few: "một vài",
  many: "nhiều",
  most: "hầu hết",
  much: "nhiều",
  such: "như vậy",
  each: "mỗi",
  every: "mỗi",
  both: "cả hai",
  either: "hoặc",
};

const yoruba = {
  a: "ọkan",
  an: "ọkan",
  the: "ẹni",
  he: "oun",
  she: "oun",
  it: "o",
  her: "tirẹ",
  his: "tirẹ",
  we: "awa",
  they: "wọn",
  me: "emi",
  us: "awa",
  them: "wọn",
  you: "ẹ",
  I: "emi",
  myself: "arami",
  yourself: "arare",
  himself: "arare",
  herself: "arare",
  itself: "arare",
  ourselves: "arawa",
  yourselves: "arare",
  themselves: "arawọn",
  who: "ta",
  whom: "ta",
  whose: "ti ta",
  which: "eyikeyi",
  what: "kini",
  someone: "ẹnikan",
  anyone: "ẹnikẹni",
  everyone: "gbogbo eniyan",
  and: "ati",
  but: "ṣugbọn",
  or: "tabi",
  nor: "tabi",
  yet: "sibẹsibẹ",
  so: "nitorina",
  however: "sibẹsibẹ",
  because: "nitori",
  although: "biotilejepe",
  though: "biotilejepe",
  since: "lati",
  if: "ti",
  unless: "ayafi",
  while: "nigba ti",
  whereas: "nigba ti",
  in: "ninu",
  on: "lori",
  at: "ni",
  by: "nipase",
  for: "fun",
  with: "pẹlu",
  to: "si",
  of: "ti",
  as: "bi",
  between: "laarin",
  through: "nipase",
  about: "nipa",
  into: "si",
  onto: "lori",
  upon: "lori",
  beside: "lẹgbẹẹ",
  behind: "lẹhin",
  within: "ninu",
  is: "ni",
  are: "ni",
  was: "jẹ",
  were: "jẹ",
  am: "ni",
  be: "jẹ",
  being: "jẹ",
  been: "jẹ",
  has: "ni",
  have: "ni",
  had: "ni",
  do: "ṣe",
  does: "ṣe",
  did: "ṣe",
  will: "yoo",
  would: "yoo",
  shall: "yoo",
  should: "yẹ",
  can: "le",
  could: "le",
  may: "le",
  might: "le",
  must: "gbodo",
  here: "nibi",
  there: "nibẹ",
  then: "nigbana",
  now: "nisiyi",
  very: "gan",
  too: "ju",
  always: "nigbagbogbo",
  never: "laelae",
  sometimes: "nigbakan",
  often: "nigbagbogbo",
  seldom: "kò",
  usually: "nigbagbogbo",
  already: "tele",
  yet: "sibẹsibẹ",
  soon: "laipẹ",
  late: "pẹ",
  this: "eyi",
  that: "pe",
  these: "awọn",
  those: "awọn",
  some: "diẹ",
  any: "eyikeyi",
  no: "rara",
  all: "gbogbo",
  few: "diẹ",
  many: "ọpọlọpọ",
  most: "julọ",
  much: "pupọ",
  such: "iru",
  each: "kọọkan",
  every: "gbogbo",
  both: "mejeeji",
  either: "eyikeyi",
};

const zhongwen = {
  a: "一个|一個",
  an: "一个|一個",
  the: "这|這",
  he: "他|他",
  she: "她|她",
  it: "它|它",
  her: "她的|她的",
  his: "他的|他的",
  we: "我们|我們",
  they: "他们|他們",
  me: "我|我",
  us: "我们|我們",
  them: "他们|他們",
  you: "你|你",
  I: "我|我",
  myself: "我自己|我自己",
  yourself: "你自己|你自己",
  himself: "他自己|他自己",
  herself: "她自己|她自己",
  itself: "它自己|它自己",
  ourselves: "我们自己|我們自己",
  yourselves: "你们自己|你們自己",
  themselves: "他们自己|他們自己",
  who: "谁|誰",
  whom: "谁|誰",
  whose: "谁的|誰的",
  which: "哪个|哪個",
  what: "什么|什麼",
  someone: "某人|某人",
  anyone: "任何人|任何人",
  everyone: "每个人|每個人",
  and: "和|和",
  but: "但是|但是",
  or: "或者|或者",
  nor: "也不|也不",
  yet: "然而|然而",
  so: "所以|所以",
  however: "然而|然而",
  because: "因为|因為",
  although: "虽然|雖然",
  though: "虽然|雖然",
  since: "自从|自從",
  if: "如果|如果",
  unless: "除非|除非",
  while: "当|當",
  whereas: "而|而",
  in: "在|在",
  on: "在|在",
  at: "在|在",
  by: "通过|通過",
  for: "为了|為了",
  with: "与|與",
  to: "到|到",
  of: "的|的",
  as: "作为|作為",
  between: "在|之间|在|之間",
  through: "通过|通過",
  about: "关于|關於",
  into: "进入|進入",
  onto: "到|上|到|上",
  upon: "在|上|在|上",
  beside: "在|旁边|在|旁邊",
  behind: "在|后面|在|後面",
  within: "在|内|在|內",
  is: "是|是",
  are: "是|是",
  was: "是|是",
  were: "是|是",
  am: "是|是",
  be: "是|是",
  being: "是|是",
  been: "是|是",
  has: "有|有",
  have: "有|有",
  had: "有|有",
  do: "做|做",
  does: "做|做",
  did: "做|做",
  will: "将|將",
  would: "将|將",
  shall: "将|將",
  should: "应该|應該",
  can: "能|能",
  could: "能|能",
  may: "可以|可以",
  might: "可能|可能",
  must: "必须|必須",
  here: "这里|這裡",
  there: "那里|那裡",
  then: "然后|然後",
  now: "现在|現在",
  very: "非常|非常",
  too: "太|太",
  always: "总是|總是",
  never: "从不|從不",
  sometimes: "有时|有時",
  often: "经常|經常",
  seldom: "很少|很少",
  usually: "通常|通常",
  already: "已经|已經",
  yet: "还|還",
  soon: "很快|很快",
  late: "晚|晚",
  this: "这个|這個",
  that: "那个|那個",
  these: "这些|這些",
  those: "那些|那些",
  some: "一些|一些",
  any: "任何|任何",
  no: "没有|沒有",
  all: "所有|所有",
  few: "少数|少數",
  many: "许多|許多",
  most: "大多数|大多數",
  much: "很多|很多",
  such: "这样的|這樣的",
  each: "每个|每個",
  every: "每个|每個",
  both: "两个|兩個",
  either: "任一|任一",
};

const serviceToTranslation = {
  afaanoromoo: mapToRegex(afaanoromoo),
  afrique: mapToRegex(afrique),
  amharic: mapToRegex(amharic),
  arabic: mapToRegex(arabic),
  azeri: mapToRegex(azeri),
  bengali: mapToRegex(bengali),
  burmese: mapToRegex(burmese),
  gahuza: mapToRegex(gahuza),
  gujarati: mapToRegex(gujarati),
  hausa: mapToRegex(hausa),
  hindi: mapToRegex(hindi),
  igbo: mapToRegex(igbo),
  indonesia: mapToRegex(indonesia),
  japanese: mapToRegex(japanese),
  korean: mapToRegex(korean),
  kyrgyz: mapToRegex(kyrgyz),
  marathi: mapToRegex(marathi),
  mundo: mapToRegex(mundo),
  naidheachdan: mapToRegex(naidheachdan),
  nepali: mapToRegex(nepali),
  pashto: mapToRegex(pashto),
  persian: mapToRegex(persian),
  pidgin: mapToRegex(pidgin),
  brasil: mapToRegex(portuguese),
  portuguese: mapToRegex(portuguese),
  punjabi: mapToRegex(punjabi),
  russian: mapToRegex(russian),
  serbian: mapToRegex(serbian),
  sinhala: mapToRegex(sinhala),
  somali: mapToRegex(somali),
  swahili: mapToRegex(swahili),
  tamil: mapToRegex(tamil),
  telugu: mapToRegex(telugu),
  thai: mapToRegex(thai),
  tigrinya: mapToRegex(tigrinya),
  turkce: mapToRegex(turkce),
  ukchina: mapToRegex(ukchina),
  ukrainian: mapToRegex(ukrainian),
  urdu: mapToRegex(urdu),
  uzbek: mapToRegex(uzbek),
  vietnamese: mapToRegex(vietnamese),
  yoruba: mapToRegex(yoruba),
  zhongwen: mapToRegex(zhongwen),
  news: mapToRegex(news),
  sport: mapToRegex(news),
  newsround: mapToRegex(news),
  bbcthree: mapToRegex(news),
  weather: mapToRegex(news),
  digihub: mapToRegex(news),
};

function mapToRegex(map) {
  const regexParts = Object.values(map).map(
    (value) => `\\b${value}\\b`
  );
  const regexString = regexParts.join("|");
  return new RegExp(regexString, "g");
}

export default (service) => {
  const formattedService = service
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/-v6/g, "");
  return serviceToTranslation[formattedService];
};

const prepositionPronounRegex =
  /\bkan\b|\bkun\b|\bkanneen\b|\ble\b|\bla\b|\bles\b|\bun\b|\bune\b|\bdes\b|\bየ\b|\bእንደ\b|\bእንዲሁም\b|\bال\b|\bفي\b|\bمن\b|\bbir\b|\bbu\b|\bo\b|\bاین\b|\bاین\b|\bاین\b|\bသည်\b|\b၏\b|\bကို\b|\bya\b|\bna\b|\bmu\b|\bઆ\b|\bતે\b|\bએ\b|\bda\b|\bna\b|\bce\b|\bयह\b|\bवह\b|\bके\b|\bnke\b|\bna\b|\bka\b|\bdi\b|\bke\b|\bdari\b|\bの\b|\bに\b|\bを\b|\b의\b|\b에\b|\b를\b|\bбул\b|\bбир\b|\bменен\b|\bहा\b|\bही\b|\bते\b|\bel\b|\bla\b|\blos\b|\blas\b|\bun\b|\buna\b|\ban\b|\bna\b|\bair\b|\bयो\b|\bत्यो\b|\bका\b|\bد\b|\bپه\b|\bله\b|\bدر\b|\bبه\b|\bاز\b|\bdi\b|\bna\b|\bwe\b|\ba\b|\bo\b|\bas\b|\bos\b|\bਇਹ\b|\bਉਹ\b|\bਦੇ\b|\bв\b|\bна\b|\bс\b|\bје\b|\bна\b|\bу\b|\bමෙම\b|\bඑම\b|\bසමග\b|\bka\b|\bku\b|\biyo\b|\bya\b|\bna\b|\bkwa\b|\bஇந்த\b|\bஅந்த\b|\bஒரு\b|\bఈ\b|\bఆ\b|\bక\b|\bที่\b|\bใน\b|\bของ\b|\bእንተ\b|\bእንታይ\b|\bእንተይ\b|\bbir\b|\bbu\b|\bol\b|\b的\b|\b在\b|\b是\b|\bв\b|\bна\b|\bз\b|\bیہ\b|\bوہ\b|\bکے\b|\bbu\b|\bshu\b|\bva\b|\bcủa\b|\blà\b|\bvà\b|\bni\b|\bati\b|\bti\b|\b的\b|\b在\b|\b是\b|\bthe\b|\bof\b|\band\b|\bto\b|\bin\b|\bthat\b|\bwith\b|\bfor\b|\bfrom\b|\bby\b|\babout\b|\ba\b|\b的\b|\b在\b|\b是\b|\b的\b|\b在\b|\b是\b|\bв\b|\bна\b|\bс\b|\bје\b|\bна\b|\bу\b|\bбу\b|\bшу\b|\bва\b/g;
