import runTestsForPage from '#nextjs/cypress/support/helpers/runTestsForPage';
import { HOME_PAGE } from '../../../../src/app/routes/utils/pageTypes';
import assertScriptSwitch from './assertions';

const testSuites = [
  // Home pages Serbian
  {
    path: '/serbian/cyr?renderer_env=live',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/lat?renderer_env=live',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Home pages Uzbek
  {
    path: '/uzbek/cyr?renderer_env=live',
    service: 'uzbek',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/lat?renderer_env=live',
    service: 'uzbek',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Home pages zhongwen
  {
    path: '/zhongwen/simp?renderer_env=live',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/trad?renderer_env=live',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Articles pages Serbian
  {
    path: '/serbian/articles/cx2g6k2k4xxo/cyr?renderer_env=live',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/articles/cx2g6k2k4xxo/lat?renderer_env=live',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Articles pages Uzbek
  {
    path: '/uzbek/articles/ce347g8zqd0o/cyr?renderer_env=live',
    service: 'uzbek',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/articles/ce347g8zqd0o/lat?renderer_env=live',
    service: 'uzbek',
    variant: 'lat',
    otherVariant: 'cyr',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Articles pages Zhongwen
  {
    path: '/zhongwen/articles/cy4lej5ep15o/trad?renderer_env=live',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/articles/cy4lej5ep15o/simp?renderer_env=live',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Topic pages Serbian
  {
    path: '/serbian/topics/c06g871g3knt/cyr?renderer_env=live',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/topics/c06g871g3knt/lat?renderer_env=live',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Topic pages Uzbek
  {
    path: '/uzbek/topics/cg72626n7yyt/cyr?renderer_env=live',
    service: 'uzbek',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/topics/cg72626n7yyt/lat?renderer_env=live',
    service: 'uzbek',
    variant: 'lat',
    otherVariant: 'cyr',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Topic pages Zhongwen
  {
    path: '/zhongwen/topics/cjnz1d612jzt/simp?renderer_env=live',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/topics/cjnz1d612jzt/trad?renderer_env=live',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Most Read Serbian
  {
    path: '/serbian/cyr/popular/read?renderer_env=live',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/lat/popular/read?renderer_env=live',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Most Read zhongwen
  {
    path: '/zhongwen/simp/popular/read?renderer_env=live',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/trad/popular/read?renderer_env=live',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // MAP Serbian
  {
    path: '/serbian/cyr/23279016',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['local', 'test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/cyr/srbija-52895074',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/lat/srbija-52895074',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/cyr/srbija-52895074',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  // MAP Zhongwen
  {
    path: '/zhongwen/simp/uk-23283128',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/trad/uk-23283128',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/simp/world-53107744',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/trad/world-53107744',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
];

runTestsForPage({
  testSuites,
});
